### ISSUE TITLE
can not find the “library section”  , so I can not add library to sample.

### ISSUE THREAD

**Issue by SeanCAAS** [TGAC/miso-lims#1156]
Hi，Friend，

I reinstall the MISO-LIMS again, and this time, I have the following question:

I can not find the "library section", so I can not add libary to sample, and in the "library' menu, I can not add library, either. 

Thank you!

Regards,

Sean

![Uploading 图片.png
[Tech Question about MISO-LIMS.pptx](https://github.com/TGAC/miso-lims/files/1339438/Tech.Question.about.MISO-LIMS.pptx)
…]()

**Comment by callunity** [comment]
Hi @SeanCAAS ,

Here are the steps to add libraries:
  * go to the Samples page
  * check the samples you wish to derive libraries from
  * click the "Propagate" button and enter the number of libraries you wish to propagate from each sample
This will take you to the bulk library entry page.

Similarly for creating dilutions, you would select the libraries you wish to derive dilutions from, click the "Make dilutions" button, and enter your dilutions details.

Please let us know if you encounter any issues with this.
Cheers,
Heather

**Comment by SeanCAAS** [comment]
Thanks a lot! Heather!

I can add library now! I am wondering does MISO-LIMS has the function to attached document (such as pdf, doc, pic or xls to the sample (or library). for example, I want to attached the original document of Bioanalyzer 2100, not just a number of insert size. Thanks!

Maybe I will have more tech questions, could you tell me you work email so I can contact with your directly! Thanks!

Regards,

Yuxiao

**Comment by callunity** [comment]
Hi Yuxiao,

MISO currently only accepts uploads to the project, not to individual samples or libraries. 

We will soon be putting together a tutorial for how to do various tasks within MISO, and I'll let you know when we've completed that. In the meantime, please continue to open issues on the project here with any questions you may have. I'll close this issue for now as you are now able to derive libraries.
