### ISSUE TITLE
Sequencer Resource Calendar

### ISSUE THREAD

**Issue by mijgmak** [TGAC/miso-lims#1157]
Hi , I've installed MISO  v. 0.2.89 and Run Scanner. When I open Sequencer Resource Calendar nothing is displayed and the buttons without function (Colour Schema, Showing Date Range), but all runs are displayed on dashbord.
Best,
Michael

**Comment by callunity** [comment]
Hi Michael,

We will be removing the Analysis and Reports tabs in the next version of MISO (v 0.2.91) as we can't guarantee that all that functionality works at present. I'd recommend commenting them out in your local `header.jsp` file.

**Comment by callunity** [comment]
PR to hide tabs: https://github.com/TGAC/miso-lims/pull/1160
