### ISSUE TITLE
Installation issue at database initialization with flyway

### ISSUE THREAD

**Issue by lbrink** [TGAC/miso-lims#1198]
One of the last steps of the described [installation procedure](https://github.com/TGAC/miso-lims/blob/develop/docs/_posts/2016-01-11-admin-manual.md) 'Migrating the database'.
This step didn't succeeded. Error was:
> SQL STATE : HY000
> Error Code : 1267
> Message: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
> Query is : `CREATE OR REPLACE VIEW BoxableView AS`
> ...

Trying to use the developer manual as a workaround went wrong too.
Both Maven targets `mvn flyway:clean` and `mvn flyway:migrate` throw the message:
> [ERROR] Failed to execute goal on project sqlstore: Could not resolve dependencies for project uk.ac.bbsrc.tgac.miso:sqlstore:jar:0.2.93: Could not find artifact uk.ac.bbsrc.tgac.miso:core:jar:0.2.93 in hasbanana-repo (http://www.hasbanana.com/maven/repo) -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project sqlstore: Could not resolve dependencies for project uk.ac.bbsrc.tgac.miso:sqlstore:jar:0.2.93: Could not find artifact uk.ac.bbsrc.tgac.miso:core:jar:0.2.93 in hasbanana-repo (http://www.hasbanana.com/maven/repo)

Any advice for me, how to work around that issue?

Thank you in advance,
Lars Brinkmann

**Comment by djcooke** [comment]
Hello,

You'll have to build the entire miso-lims project (`mvn clean install -P external`) from the root directory before running the Maven Flyway plugin. I think it's likely that you'll experience the same error as with the Flyway command-line tool, in which case you might want to try configuring your MySQL server to use `utf8` charset and `utf8_general_ci` collation.

**Comment by lbrink** [comment]
Thank you for the fast response.
I build it with the command from admin-guide (`mvn clean package -P external`).
I've re-build  with `install` option successfully.
Both Flyway goals (`mvn flyway:clean` and `mvn flyway:migrate`) succeeded afterwards.
My error, didn't read the dev manual carefully enough.

One issue remains: While I'm a developer I wanted to install the MISO instance as an administrator.
So I'm a bit concerned about the fact that I need so much developer knowledge for the installation and still have to ask for individual support.
The collation issue I ran into following the admin manual is something I could fix with my skills. But I hardly can decide which collation would be the correct one. For this decision I would need deeper knowledge of database scheme.

While I'm not able to improve the admin guide atm, I think it would greatly increase the value of MISO.
At this place I wan't to say thank you to all contributors. Great job.
