### ISSUE TITLE
Problem with Miso DB

### ISSUE THREAD

**Issue by soporteCluster** [TGAC/miso-lims#1207]
Hi 
We work with an investigation group who needs to use Miso-Lims so we had to install it. When we installed it the program work well but sometimes the software suddenly stop working.  Its appear that it can't connect with the Database because it stay like thinking but nothing happens, and not show anything (we attach a picture with this state).
To resolve this we tried remove and restore ROOT.war, check files permissions, reload tomcat and mysql, and much more with no good results. We were searching for some soluttions but doesn't find much information about this problem.
We think the problem is the database because if we create a new blank database and assigns it to MISO  the program start well but obviously with no data loaded.
We have installed Miso on a computer with Centos 7, Java 8, Tomcat 8 and mysql 5.7.
could any of you help us?
Very Thanks

**Comment by djcooke** [comment]
Hello,

We'll need more information to be of much assistance. Which version of MISO are you running? Can you check `miso_debug.log` (in the `log` directory inside your configured `miso.baseDirectory`) and the Tomcat logs for errors?

**Comment by soporteCluster** [comment]
Hi,
Very thanks for your reply. We have the Version: 0.2.1-SNAPSHOT. About logs none of them shows any problem. Below we attach an image of the state of miso.
![miso](https://user-images.githubusercontent.com/26146311/33083657-beb433ec-cebe-11e7-8684-230146f6b1b9.png)

**Comment by djcooke** [comment]
The version you are using is not a release version of MISO, and is very likely unstable. I can see that the documentation does not make this obvious, and we will fix it to clarify.

Do you have existing data from this MISO version that needs to be maintained? If not, the easiest option is to install the latest version of MISO from the [Releases section](https://github.com/TGAC/miso-lims/releases) and start with a fresh database. If you do have data that must be maintained, Flyway can be used to migrate your database to the latest version.

**Comment by soporteCluster** [comment]
I'm trying to install a new instance of MISO, with a clean Database. 
I have a problem when i execute the flyway command:
./flyway -user=tgaclims -password=tgaclims -url=jdbc:mysql://localhost:3306/lims -outOfOrder=true -locations=classpath:db/migration,classpath:uk.ac.bbsrc.tgac.miso.db.migration migrate

The error message is:
ERROR: 
Migration afterMigrate.sql failed
---------------------------------
SQL State  : HY000
Error Code : 1267
Message    : Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
Query is : CREATE OR REPLACE VIEW BoxableView AS
SELECT a.*, bp.boxId, bp.position AS boxPosition, b.name AS boxName, b.alias AS boxAlias, b.locationBarcode AS boxLocationBarcode
FROM (
    SELECT s.sampleId AS targetId, 'SAMPLE' AS targetType, s.name, s.alias, s.identificationBarcode, s.locationBarcode, s.volume,
        s.discarded, ds.preMigrationId, ds.sampleClassId
        FROM Sample s
        LEFT JOIN DetailedSample ds ON ds.sampleId = s.sampleId
    UNION ALL
    SELECT l.libraryId, 'LIBRARY', l.name, l.alias, l.identificationBarcode, l.locationBarcode, l.volume, l.discarded, dl.preMigrationId,
        NULL
        FROM Library l
        LEFT JOIN DetailedLibrary dl ON dl.libraryId = l.libraryId
    UNION ALL
    SELECT dilutionId, 'DILUTION', name, name, identificationBarcode, NULL, volume, discarded, preMigrationId, NULL
        FROM LibraryDilution
    UNION ALL
    SELECT poolId, 'POOL', name, alias, identificationBarcode, NULL, volume, discarded, NULL, NULL
        FROM Pool
) a
LEFT JOIN BoxPosition bp ON
Location   : db/migration/afterMigrate.sql (/opt/flyway/file:/opt/flyway/lib/sqlstore-0.2.97.jar!/db/migration/afterMigrate.sql)
Line       : 1240
Statement  : CREATE OR REPLACE VIEW BoxableView AS
SELECT a.*, bp.boxId, bp.position AS boxPosition, b.name AS boxName, b.alias AS boxAlias, b.locationBarcode AS boxLocationBarcode
FROM (
    SELECT s.sampleId AS targetId, 'SAMPLE' AS targetType, s.name, s.alias, s.identificationBarcode, s.locationBarcode, s.volume,
        s.discarded, ds.preMigrationId, ds.sampleClassId
        FROM Sample s
        LEFT JOIN DetailedSample ds ON ds.sampleId = s.sampleId
    UNION ALL
    SELECT l.libraryId, 'LIBRARY', l.name, l.alias, l.identificationBarcode, l.locationBarcode, l.volume, l.discarded, dl.preMigrationId,
        NULL
        FROM Library l
        LEFT JOIN DetailedLibrary dl ON dl.libraryId = l.libraryId
    UNION ALL
    SELECT dilutionId, 'DILUTION', name, name, identificationBarcode, NULL, volume, discarded, preMigrationId, NULL
        FROM LibraryDilution
    UNION ALL
    SELECT poolId, 'POOL', name, alias, identificationBarcode, NULL, volume, discarded, NULL, NULL
        FROM Pool
) a
LEFT JOIN BoxPosition bp ON bp.targetId = a.targetId AND bp.targetType = a.targetType
LEFT JOIN Box b ON b.boxId = bp.boxId

I made what was proposed in:
https://github.com/TGAC/miso-lims/issues/1198

So first i execute:
mvn clean install -P external

And then the flyway migration:
./flyway -user=tgaclims -password=tgaclims -url=jdbc:mysql://localhost:3306/lims -outOfOrder=true -locations=classpath:db/migration,classpath:uk.ac.bbsrc.tgac.miso.db.migration migrate

But i had the same error again.

**Comment by soporteCluster** [comment]
I made a new installation with a clean database. All seemed to be OK but when i try to create a new library i have the following error:
![error library](https://user-images.githubusercontent.com/26146311/33277405-32974206-d377-11e7-93ca-48e9c95e6fad.png)

**Comment by djcooke** [comment]
I see why this is happening, and will have a fix in shortly. The issue only affects library receipt. You should still be able to create samples, and then propagate libraries from them

**Comment by djcooke** [comment]
The fix is in and should be included in the next release: https://github.com/TGAC/miso-lims/pull/1218

Thanks for the bug report. Please let us know if you experience any other issues
