### ISSUE TITLE
Package MISO configuration files with distribution

### ISSUE THREAD

**Issue by alanorth** [TGAC/miso-lims#1212]
It's strange to have to download the MISO configuration properties from an external URL. These should be provided by the distribution, for example in a "contrib" directory or something. For reference, I mean the four property files provided by [miso_userspace_properties.tar.gz](https://repos.tgac.ac.uk/miso/latest/miso_userspace_properties.tar.gz) that are part of the install process documented in the [admin manual](https://github.com/TGAC/miso-lims/blob/develop/docs/_posts/2016-01-11-admin-manual.md).

**Comment by callunity** [comment]
Thanks for raising this, @alanorth  - it has been on our to-do list for a while, but hadn't quite made it to the top. I've now made a [pull request](#1228) that adds the properties files into MISO; these changes should show up in release v0.2.101.
