### ISSUE TITLE
Create new user

### ISSUE THREAD

**Issue by soporteCluster** [TGAC/miso-lims#1225]
Hi,
I have a problem when i try to create the first new user in MISO. 
I click "Add" , then i complete all the fields and when i try to save i have the following error:
![pantallazo](https://user-images.githubusercontent.com/26146311/33625275-d391ee36-d9d5-11e7-8cdb-d31d6346f575.png)
I have the MISO version 0.2.97, and i'm logging as "admin"
Very thanks,

**Comment by djcooke** [comment]
Thanks for the report. I have a fix for this that will be in pull request shortly.

**Comment by djcooke** [comment]
Fix: https://github.com/TGAC/miso-lims/pull/1226
Will be included in MISO release 0.2.102
