### ISSUE TITLE
config: runscanner / runscanner-illumina

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1233]
Hi,
In the `Runs` overview it seems that the runs are not updated. E.g. the NextSeq runs are still all *Running* (as old MISO couldn't determine the correct run status for NextSeq).

I put `<Parameter name="runscanner.configFile" value="/path/to/runscanner.json" override="false"/>` into its own `runscanner.xml`. The json file contains the correct (read-only) paths to the sequencer run data.

Additionally I wanted to see some InterOp stats for Illumina Runs.

I built the `runscanner-illumina` (from tags/v0.2.100) as described and put it in $PATH before I started tomcat/MISO.  Here I get only "No graphs available." (Metrics).

I found an error in `localhost.2017-12-12.log`:
```
12-Dec-2017 14:15:10.325 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of cla
ss [org.springframework.web.util.Log4jConfigListener]
 java.lang.IllegalStateException: Web app root system property already set to different value: 'webapp.root' = [/scratch/local2/build/miso2017/tomcat/webapps/ROOT/] instead of [/scra
tch/local2/build/miso2017/tomcat/webapps/runscanner/] - Choose unique values for the 'webAppRootKey' context-param in your web.xml files!
```
What is going wrong here?

EDIT:

OK, I probably missed something of `runscanner` concept ...

How must the `miso.properties` be set?
```
2017-12-12 15:10:07 ERROR: Failed to get runs from http://lammkarree:8809/runscanner
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://lammkarree:8809/runscanner/runs/progressive": Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from server
```
I used `miso.runscanner.urls:http://lammkarree:8809/runscanner` where `lammkarree` is my linux workstation running the MISO test instance.

The ports have been configured (here for testing) in `server.xml`,
```
<Server port="8805" shutdown="SHUTDOWN">
<Connector port="8088" protocol="HTTP/1.1" connectionTimeout="20000" redirectPort="8443" />
<Connector port="8809" protocol="AJP/1.3" redirectPort="8443" />
```

**Comment by sklages** [comment]
Probably I didn't understand well how to setup runscanner/runscanner-illumina after reading [1]/[2].

It is surely a very basic issue ... but currently I'm stuck ...

[1]=https://github.com/TGAC/miso-lims/tree/develop/runscanner
[2]=https://github.com/TGAC/miso-lims/tree/develop/runscanner-illumina

**Comment by apmasell** [comment]
Are you deploying run scanner on the same system as MISO? It needs to be put on a different machine.

**Comment by sklages** [comment]
Ok. I wasn't aware of that. Docs state both. If run on the same machine, i need to create runscanner.xml, on a remote machine I need to extend ROOT.xml.

**Comment by callunity** [comment]
I apologize for the error, @sklages  - when I updated the documentation, I had thought that it was possible to deploy both on the same machine. Will update the documentation to reflect that this is not possible.
