### ISSUE TITLE
Q: "Orders" and "Boxes"

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1235]
There are two new entries in the navigation pane. 

**Boxes** - just a physical location (=box) for samples, tissues etc? In the sample tab there is a free text "Location" and a corresponding "Box Location". <br>
E.g. Box `ABC` containing `SAMPLE_A` is located in tower 1, room 22, freezer 7, compartment 1 (=Location). The sample itself is located at position A12 in a 96er matrix within the box (=Box Location)?

**Orders** - where are orders positioned in the MISO sequencing workflow? What is their purpose here? Usually we had libraries put together in a pool which is diluted and put on a flowcell. <br>
Is it something like: these pools are ready to go on a  sequencer. These pools have special requirements, e.g. HiSeq4000 only, or PE151 or dual indexing etc. Just some kind of pre-run organisation (which is probably necessary with NovaSeq6000)?

Just want to be sure to get things right and, even more important, to "sell" things right to my colleagues in the lab ;-)

**Comment by djcooke** [comment]
Boxes are a physical location for samples, libraries, dilutions, and pools, with box positions like A12 as you mentioned. The other location text field is for when things are stored in different way that needs to be described differently. A box position is preferred for a sample if that's how it is stored, and the box itself can be given a location in free text, which may include things like the tower, room, freezer, etc.

Your description of an order is correct. When a pool is ready for sequencing, an order can be created to indicate this, along with required sequencing parameters.

**Comment by callunity** [comment]
@sklages the "2.0 Scan samples into your inbox", "4 Scanning libraries into your outbox", and "7 Order Sequencing" sections on the [walkthrough](http://oicr-gsi.github.io/miso-docs-oicr/plain-3-0-libraries) (as well as "5.1 Add a Pool to a Run" from the [sequencing section](http://oicr-gsi.github.io/miso-docs-oicr/plain-4-0-sequencing)) may be useful for seeing how we use these in our workflows.

**Comment by callunity** [comment]
@sklages do you have any further questions about boxes or orders?

**Comment by sklages** [comment]
@callunity - not yet, thanks :-)
