### ISSUE TITLE
External Interface: miso-external.war

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1236]
When compiling MISO there is also a `miso-external.war` created. 
How can I use / setup this external access?

In our sequencing core  MISO is exclusively accessed by our lab... Customers provide samples and sequencing requests externally (excel sheets). All data is entered by the lab team.

Does this `miso-external` only provide (controlled) read access to MISO database or does it also provide the possibility for a customer to provide sequencing orders / sample information?

**Comment by callunity** [comment]
Hi @sklages , the `miso-external` section was indeed originally intended to provide (controlled) read-only access to MISO data, so the customer would not be able to enter information. It looks like the `miso-external` section is not currently functional, and fixing it is not a priority for us right now.

**Comment by sklages** [comment]
OK, good to know. Thanks.
