### ISSUE TITLE
Samplesheet (custom) format

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1237]
The samplesheet which can be created in the webinterface has a somewhat ancient format.
```
FCID,Lane,SampleID,SampleRef,Index,Description,Control,Recipe,Operator,Project
CB99WANXX,1,347_LIB6218_LDI5830,mpimg_S11311_DMSO-DMSO,TGACCA,DMSO-DMSO,N,NA,klages,prj1
CB99WANXX,1,347_LIB6531_LDI6039,mpg_S11548_H-O-1,CTCTCTAC-TAGATCGC,H-O-1,N,NA,klages,prj2
CB99WANXX,1,347_LIB6529_LDI6037,mpg_S11546_H-Y-1,GGACTCCT-TAGATCGC,H-Y-1,N,NA,klages,prj2
CB99WANXX,1,347_LIB6340_LDI5928,mpimg_S11347_M3-21.8,GGCTAC,M3-21.8,N,NA,klages,prj3
```

Our samplesheet (created from the command line) looks like this:
```
Lane,Sample_ID,Sample_Name,Sample_Plate,Sample_Well,I7_Index_ID,index,I5_Index_ID,index2,Sample_Project,Description
1,mpimg_L11311-1_DMSO-DMSO,mpimg_L11311-1_DMSO-DMSO,,,4,TGACCA,,,prj1,SAMPLE_DESCRIPTION + SAMPLE_ID + whatever
1,mpg_L11548-1_H-O-1,mpg_L11548-1_H-O-1,,,N707,CTCTCTAC,N501,TAGATCGC,prj2,SAMPLE_DESCRIPTION + SAMPLE_ID + whatever
1,mpg_L11546-1_H-Y-1,mpg_L11546-1_H-Y-1,,,N705,GGACTCCT,N501,TAGATCGC,prj2,SAMPLE_DESCRIPTION + SAMPLE_ID + whatever
1,mpimg_L11347-1_M3-21_8,mpimg_L11347-1_M3-21_8,,,11,GGCTAC,,,prj3,SAMPLE_DESCRIPTION + SAMPLE_ID + whatever
```

When creating a NextSeq 500 samplesheet we omit the first column.

   * Would it possible to have this configurable? E.g. where I can select which column show up in samplesheet creation?
   * alternatively, where can this be changed in the source code, so I can change this by myself (for either 1.7 or 1.8 button)?

**Comment by callunity** [comment]
Hi @sklages ,

You could make the changes in the [SampleSheet.java](https://github.com/TGAC/miso-lims/blob/develop/core/src/main/java/uk/ac/bbsrc/tgac/miso/core/util/SampleSheet.java) file, and it should be straightforward to change either or both the 1.7 and 1.8 version.

**Comment by sklages** [comment]
OK, I'll do my best :-)

**Comment by sklages** [comment]
hmm, .. not that easy as I thought.

Would it be possible for you to provide a modified version of SampleSheet.java (CASAVA_1_7 or CASAVA_1_8) returning the following columns:

Stream.of("Lane", "Sample_ID", "Sample_Name", "I7_Index_ID","index","I5_Index_ID","index2","Sample_Project","Description", "Operator");

where Sample_ID = Sample_Name is actually the "Library Alias", e.g. "mpimg_L11497-1_201710-MRA-OJ-002".

Thank you.

**Comment by sklages** [comment]
As I need samplesheet on the command line I fetch the relevant data from the database with a custom perl script (from the command line).

**Comment by morgantaschuk** [comment]
Hi Sven. The team mentioned you had a couple of feature requests that aren't on our current roadmap. Could you email me to talk about some options for getting the features you want? My email address is morgan.taschuk@oicr.on.ca

**Comment by abaano** [comment]
Any plans to accommodate the new fields in the samplesheet per Illumina. https://www.illumina.com/content/dam/illumina-marketing/documents/products/technotes/sequencing-sheet-format-specifications-technical-note-970-2017-004.pdf

**Comment by morgantaschuk** [comment]
Re-opening this because we are adding more types of sample sheets.
