### ISSUE TITLE
Alter User: password needed

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1242]
When I am logged in with `admin` privileges, I'd expect to `activate` or `deactivate` users without knowing their passwords.

Currently I have to fill in the user's password to deactivate the user's  account.

**Comment by callunity** [comment]
Thanks for raising this, @sklages . We'll add it to our backlog.

**Comment by djcooke** [comment]
This was just recently fixed: https://github.com/TGAC/miso-lims/pull/1226
