### ISSUE TITLE
Dashboard: "Projects" shows only PRO1 to PRO50

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1244]
The dashboard usually shows the latest items. But for "Projects" it shows only PRO1 to PRO50, although we currently have 62 projects.

"My Projects" tab works just as intented.

Version 0.2.100

**Comment by callunity** [comment]
The dashboards only pull 50 items at a time, but are fully searchable. I suppose it would make more sense to pull the 50 most recent projects as opposed to the 50 first ones.

**Comment by callunity** [comment]
PR is #1245 .
