### ISSUE TITLE
"Create Libraries from Samples": Size is stored, Conc not

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1261]
When creating libraries from samples, I have the possibility to also provide "Size" and "Conc".
But only "Size" is stored in the library, "Conc" is not.

**Comment by djcooke** [comment]
Hi Sven,

Libraries do have a concentration field. It is visible on the bulk edit page. You will not see it on the single Edit Library page right now because it is misplaced. This is fixed by PR https://github.com/TGAC/miso-lims/pull/1264
