### ISSUE TITLE
runscanner / runscanner-illumina: Info / Configuration

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1262]
I have several questions about runscanner and runscanner-illumina.

#### runscanner
`runscanner` itself just looks into configured raw run directories (e.g. Illumina) and reports if a run is running or has finished (or reports error). Runs not having status "Running" are not updated?

`runscanner-illumina` provides some SAV-like data for visual inspection.

Is that correct so far?

#### configuration
I have installed tomcat on a separate machine and deployed runscanner as described in [1].

URL : `http://myserver:8088/runscanner`

I have put this URL in `miso.properties` of our MISO installation.

The runscanner URL shows some overview.

`Is Configuration Good?` -> false  :confused:

The runscanner's ROOT.xml points to readable runscanner.json file.
(`<Parameter name="runscanner.configFile" value="/project/miso/current/config/runscanner.json" override="false"/>`)

The json file itself contains entries like:
```
  {
    "path": "/path/to/illumina/machine/SN106",
    "platformType": "ILLUMINA",
    "checkOutput": true,
    "name": "SN106",
    "timeZone": "Europe/Berlin",
    "parameters": {}
  },
  ```

All subpages like "Failed", "Instruments" etc. just show `No directories.`.

So there is something wrong with my configuration. 

#### runscanner-illumina
I have built runscanner-illumina just as described in [2]

Now `runscanner-illumina` is in $PATH of runscanner user on runscanner machine .. 
How is this used or integrated? Or is this just some program that could be integrated if someone writes some code to integrate it? ;-)

[2] didn't help (me) much ...

   * [1] = https://github.com/TGAC/miso-lims/blob/develop/docs/_posts/2016-01-11-admin-manual.md
   * [2] = https://github.com/TGAC/miso-lims/tree/develop/runscanner-illumina

**Comment by djcooke** [comment]
`runscanner-illumina` is fully functional. We use it in production at OICR. As you pointed out, Run Scanner is telling you there is a problem with your configuration. Can you post your full `runscanner.json`? Reducing your config to a single (Illumina) path may simplify troubleshooting as well.

**Comment by sklages** [comment]
```json
[
  {
    "path": "/project/solexadata/machine/SN106",
    "platformType": "ILLUMINA",
    "checkOutput": true,
    "name": "SN106",
    "timeZone": "Europe/Berlin",
    "parameters": {}
  },
  {
    "path": "/project/solexadata/machine/SN367",
    "platformType": "ILLUMINA",
    "checkOutput": true,
    "name": "SN367",
    "timeZone": "Europe/Berlin",
    "parameters": {}
  },
  {
    "path": "/project/solexadata/machine/SN442",
    "platformType": "ILLUMINA",
    "checkOutput": true,
    "name": "SN442",
    "timeZone": "Europe/Berlin",
    "parameters": {}
  }
]
```

Three different sequencers, all paths are readable (not writable). SN106/SN367/SN442 are symlinks.

**Comment by sklages** [comment]
OK, .. I am moving forward, slowly but surely ..

log says: 
```
ERROR   2018-01-04 13:25:57,823 [pool-1-thread-1] 
uk.ac.bbsrc.tgac.miso.runscanner.Scheduler  - Confguration is bad.
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: 
Unrecognized field "checkOutput" 
(class uk.ac.bbsrc.tgac.miso.runscanner.Scheduler$SuppliedDirectoryConfig), 
not marked as ignorable 
(5 known properties: "timeZone", "parameters", "name", "path", "platformType"])
 at [Source: /project/miso/current/config/runscanner.json; line: 5, column: 24]
```
I removed `"checkOutput": true,` as this is obviously the problem. 

Now I get `Is Configuration Good? -> true`. OK.

At the bottom of the page it is showing three paths to three sequencer data directories.
`ProcessorName` and `Platform` are empty and the `Valid?` column states **false**.

It still seems that runscanner is not yet working (properly).

runscanner-illumina neither.

**Comment by djcooke** [comment]
The "name" attribute is the name of the processor to use for scanning the directories. You should set it to "default" for all three directories. Instrument names don't need to be configured, as they can be found in the run data.

The "parameters" attribute is for additional parameters specific to a processor, and should be left empty for these, as the default Illumina scanner takes no additional parameters. The default PacBio processor requires an additional parameter for the webservice URL.

**Comment by sklages** [comment]
Ah, okay. That was simple, cool.. now all runs show up in "Finished". `Valid?` is **true** now.

There were quite some runs migrated from old database with wrong "Status". E.g. NextSeq runs are still all "Running" and HiSeq 4000 runs are "Unknown". 

I think I found the problem in `miso_debug.log`:
```
For our NextSeq500:
[..]IllegalArgumentException: No such sequencer: NS500442

For our HiSeqs:
[..]IllegalArgumentException: No such sequencer: K00367
[..]IllegalArgumentException: No such sequencer: D00106
```
We do name all our sequencers **SN** followed by the last three digits of the serial number. 
So NS500442 is SN442, K00367 is SN367 and D00106 is SN106. We will do so for our NovaSeq as well.

This SN-tag can be found in runfolder names and also in miso's sequencers list. But in the sequencer's XML files you will still find the original serial number.

We cannot change this as too many things depend on that. But that probably prevents runscanner from working properly... 

Do you see any workaround?

And I assume if runscanner is running properly than runscanner-illumina will do so as well ...

**Comment by djcooke** [comment]
Run Scanner will use the instrument name from the XML. There is no mechanism for translating this to a preferred name.

If the status changes you mentioned came from the Run Scanner:
* There was a bug with detecting NextSeq run completion, and a fix is in for version 0.2.103.
* HiSeq runs are reported as 'Unknown' if Run Scanner is unable to determine the correct status. These runs should be manually set to Completed or Failed. Run Scanner will not overwrite the status if it was changed by a user

**Comment by sklages** [comment]
What are the consequences of the above mentioned error? Will runscanner find and report the status anyway? Is "Run Scanner is unable to determine the correct status" due to sequencer name mismatches?

**Comment by djcooke** [comment]
With the current NextSeq bug, runs will still be detected as Running after they've been Completed. The runs can be set to Completed by a user, and Run Scanner will not overwrite the user-set status.

Name mismatches won't affect Run Scanner's ability to detect run status, but when it reports the run to MISO, MISO will fail to save the run if the sequencer doesn't exist.

**Comment by sklages** [comment]
So it should (at least temporarily) help to simply rename the sequencers in MISO?
Within the UI the sequencer names are not especially important for the user...

**Comment by djcooke** [comment]
Yes, renaming the sequencers in MISO will allow the runs reported by Run Scanner to be saved/updated in MISO

**Comment by sklages** [comment]
What will be read in this case, "Serial Number" or "Name"?

**Comment by djcooke** [comment]
The instrument's "name" attribute in MISO must match

**Comment by sklages** [comment]
oh, .. I see the first run collected by runcanner 👍  The metrics graphics shown are generated by runscanner-illumina (called intensities, cluster densities etc.)?

**Comment by sklages** [comment]
Is there a way to force re-scanning of all/some runfolders? The already existent (migrated from old MISO) runfolders do not contain any metrics data/graphics.

**Comment by sklages** [comment]
runscanner is now working as intented.

**Comment by djcooke** [comment]
The NextSeq run completion detection bug did not affect all runs
