### ISSUE TITLE
Symbolic links are resolved

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1263]
MISO is resolving symbolic links.

E.g.  our runs are stored on different jbods, jb001, jb002 etc.  We point to these storage volumes with symlinks.

`/project/data/run1 -> /project/jb001/run1`

MISO always shows `/project/jb001/run1`, but this location is not guaranteed to be stable. 
`/project/data/run1` is stable and will always be..

I think most users want to see their symlink names here IMHO.

**Comment by djcooke** [comment]
Makes sense. Just to clarify, you are talking about run paths reported by Run Scanner, right? i.e. you configure Run Scanner to scan `/project/data/` and it reports a path of `/project/jb001/run1` instead of `/project/data/run1`

**Comment by sklages** [comment]
Yes. Not sure if runscanner created this or if this has been migrated from old database scheme.

**Comment by sklages** [comment]
For the first scanned run (all other run have been migrated from old MISO) it seems that it shows the (correct) symlink name. So maybe this was an issue with old MISO? 
Version: 0.2.102

**Comment by djcooke** [comment]
Closing this issue as it seems to be in the past. Please reopen if this does happen with current Run Scanner
