### ISSUE TITLE
Q: How to best add/modify/delete LibrarySelection/Strategy

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1268]
What is the preferred way to add/modify/delete library selection and strategy methods?
Simply inserting or deleting in the database doesn't seem to make the trick ..

**Comment by djcooke** [comment]
Insert/delete in database should work fine, but the values are cached briefly. They should update within 15 minutes.

**Comment by djcooke** [comment]
@sklages: Did waiting solve the problem, or are the entries still not appearing after 15 minutes?

**Comment by sklages** [comment]
Yes, it did the trick 👍
