### ISSUE TITLE
Wrong Library numbering?

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1269]
When creating a library from a sample, the library becomes `-2`. I would expect the first library created to be `-1`.

E.g.:

Sample `mpg_S11641_SampleA`

First library `mpg_L11641-2_SampleA`, but I would expect `mpg_L11641-1_SampleA`.

**Comment by djcooke** [comment]
This is a bug in the `DefaultLibraryAliasGenerator`. Will fix

**Comment by djcooke** [comment]
Fix submitted: #1271
