### ISSUE TITLE
Overview "Sequencing Containers" sorting order

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1270]
Just another sorting issue:

The "Sequencing Containers" table should be initially sorted by "Last Run Alias" upon opening.
And the columns "Last Run Name" and "Last Run Alias" should be sortable.

**Comment by djcooke** [comment]
Is there a purpose to this that the Runs page isn't better suited for?

**Comment by sklages** [comment]
The run page is definitely better suited.

It's more like: there is a table, this table could be sorted, and if it is sorted, there should be a way to sort it in a different way  :blush:
