### ISSUE TITLE
Q: Move sample to another project

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1285]
There is no way (in the UI) to move samples from one project to another.

Is it safe to to this directly in the database, e.g.
```
UPDATE Sample SET project_projectId='20' WHERE sampleId='1';
```
I can, however, call `deleteSample()` and then freshly create these samples in another project.
But this only works (efficient) directly after sample creation (when there are no libs or QCs yet).

**Comment by djcooke** [comment]
It is safe to do the move directly in the database. Keep in mind that libraries and dilutions are linked to the same project as their sample, so moving the sample will also move its libraries and dilutions. You should update the lastModifier and lastModified fields at the same time to generate an accurate changelog entry:

```
UPDATE Sample SET
project_projectId = 123,
lastModified = NOW(),
lastModifier = (SELECT userId FROM User WHERE loginName = 'sklages')
WHERE sampleId = 456;
```

(substitute the correct projectId, sampleId, and username)

**Comment by sklages** [comment]
Thanks 👍
