### ISSUE TITLE
flybase migration:  Duplicate entry 'XXX' for key 'uk_pool_alias'

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1298]
I updated MISO from v0.2.104 to v0.2.105 and encountered the following issue (which has not been reported in former migrations):
```
Migrating schema `miso_seqcore` to version 0410 - auto main
ERROR: Migration of schema `miso_seqcore` to version 0410 failed! Please restore backups and roll back database and code!
ERROR: 
Migration V0410__auto_main.sql failed
-------------------------------------
SQL State  : 23000
Error Code : 1062
Message    : Duplicate entry 'MP2_P487_FischerPool-41' for key 'uk_pool_alias'
Location   : db/migration/V0410__auto_main.sql (/project/miso/2018/build_tools/flyway/3.2.1/file:/project/miso/2018/build_tools/flyway/3.2.1/lib/sqlstore-0.2.104.jar!/db/migration/V0410__auto_main.sql)
Line       : 3
Statement  : ALTER TABLE Pool ADD CONSTRAINT uk_pool_alias UNIQUE (alias)
```

Indeed there were 15 pools (out of 1400) with identical pool aliases. I have fixed that in the database and repeated migration. It worked fine now.

Why did migration fail? It should be possible to have identical `alias`es (the same is pretty valid for other things like samples, libs etc), that's why there are IDs ...

**Comment by djcooke** [comment]
We've added the requirement for pool aliases to be unique due to the potential for confusion. Mainly, it can be costly if the wrong Pool ends up getting run.

**Comment by sklages** [comment]
Ok, makes sense.
