### ISSUE TITLE
Broken UI with Version: 0.2.106 - Not usable

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1318]
I just compiled Version: 0.2.106 and deployed it. 

```
[INFO] Reactor Summary:
[INFO] 
[INFO] MISO LIMS .......................................... SUCCESS [  1.237 s]
[INFO] MISO Core .......................................... SUCCESS [ 26.772 s]
[INFO] MISO Integration Tools ............................. SUCCESS [ 23.495 s]
[INFO] miso-dto ........................................... SUCCESS [  4.572 s]
[INFO] MISO SQL Store ..................................... SUCCESS [ 29.849 s]
[INFO] miso-service ....................................... SUCCESS [  4.953 s]
[INFO] MISO Spring IoC .................................... SUCCESS [ 16.355 s]
[INFO] MISO MVC ........................................... SUCCESS [01:14 min]
[INFO] MISO Run Scanner ................................... SUCCESS [  6.590 s]
[INFO] miso-external-web .................................. SUCCESS [  3.304 s]
[INFO] migration .......................................... SUCCESS [02:25 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
Compilation went fine and database migration was not necessary (`Schema miso_seqcore is up to date. No migration necessary.`)

But this results in an usable MISO, e.g `Runs` returns:
```
could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
[stacktrace]
```

All other pages are simply empty :-(

So I will go back to `0.2.105` .. 

Any idea what is going wrong?

**Comment by sklages** [comment]
Interestingly, when giong back to `0.2.105` I get the same error now :-(

**Comment by djcooke** [comment]
Hi Sven,

0.2.106 had some schema changes and a migration is definitely necessary. Are you sure Flyway was run using the correct MISO version?

**Comment by sklages** [comment]
OK, I started with building:
```
[...]
[INFO] ------------------------------------------------------------------------
[INFO] Building MISO LIMS 0.2.106
[INFO] ------------------------------------------------------------------------
[...]
```
got:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
deploying:
```
[...]
Created compressed database backup.
 Path    : /project/miso/current/backup
 File(s) : miso.20180207_173023.database.sql.gz

Archive:  /project/miso/current/tomcat/webapps/ROOT.war
 extracting: lib/sqlstore-0.2.105.jar  
Flyway 3.2.1 by Boxfuse

Database: jdbc:mysql://localhost:3307/miso_seqcore (MySQL 5.7)
Validated 73 migrations (execution time 00:00.141s)
[...]
```

I deployed from checked-out branch (0.2.106) .. I thought .. at least it showed "Version: 0.2.106" at the bottom of Home tab.

Migration is done with (before copying ROOT.war):
```
migrate_database () {
    FW_VERSION="3.2.1"
    cd $MISO_HOME/build_tools/flyway/$FW_VERSION
    rm -f lib/sqlstore-*.jar
    unzip -xjo $CATALINA_HOME/webapps/ROOT.war 'WEB-INF/lib/sqlstore-*.jar' -d lib
    ./flyway \
      -user=root \
      -password=Maeatu1N \
      -url=jdbc:mysql://localhost:3307/miso_seqcore \
      -outOfOrder=true \
      -locations=classpath:db/migration,classpath:uk.ac.bbsrc.tgac.miso.db.migration \
      migrate
}
```


I will have to install a new testing instance as my little test computer has been removed.
I will then try to reproduce and report back ..

**Comment by djcooke** [comment]
It looks like you're extracting the old sqlstore jar from ROOT.war before copying the new ROOT.war?

**Comment by djcooke** [comment]
I edited your post to hide your password

**Comment by sklages** [comment]
thanks, it was a quick copy&paste. 

hmm,ok, yes. I migrate the database as described. That means I do extract the current (here 0.2.105) sqlstore-*.jar from ROOT.war.
I never thought about that. 
That's how it is described in [Admin Manual](https://github.com/TGAC/miso-lims/blob/develop/docs/_posts/2016-01-11-admin-manual.md) under `Releasing and Upgrading`. Or at least that's how I understood.

**Comment by djcooke** [comment]
Ah, I see. Those steps are out of order in the Admin Manual. I'll fix that

**Comment by sklages** [comment]
That might explain some issues I had before when migrating the database .. :-)

**Comment by djcooke** [comment]
Docs fixed in PR. Does 0.2.106 work after migrating using the correct version?

**Comment by sklages** [comment]
Yes, it works like a charm. Such a simple issue. 
I never questioned the admin update procedure; I should have looked a bit closer, then I would have noted too that the order is not correct :-)
