### ISSUE TITLE
Q: Release Notes  v0.2.106 - "other instruments"

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1323]
v0.2.106 release notes state: `Separated sequencers from other instruments`.

What is "other instruments" referring to? What instruments you are planning to integrate into MISO?

**Comment by djcooke** [comment]
0.2.106 separates Instruments into

* Sequencers: to be used for Sequencer Runs
* Other: any non-sequencing instruments you want to add to MISO to track Service Records, or for any other purpose. These instruments will no longer show up as targets for Sequencer Runs

0.2.107 will add Array Scanners (e.g. Illumina iScan) to be used for Array Runs
