### ISSUE TITLE
Q: Instrument Status

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1342]
What is the `Instrument Status` referring to? Just pinging the IP associated with each instrument? If so, that's not really a *status* ... 

And why is there a big black pic with a question mark showing up in the instrument's `Runs` table?

The same huge question mark sign shows up in the run overview above the table as well.

oh, it seems that is some kind of search box, it shows ...

```
Search syntax: 
is:RUNSTATUS
created:DATE
changed:DATE
creator:USER
changedby:USER
platform:PLATFORM
index:NAME
index:SEQ
```
See https://ws.molgen.mpg.de/ws/665777/Screenshot_20180218_161133.png

Compilation and database migration of version 0.2.107 worked without errors.

**Comment by sklages** [comment]
Hmm, I see that this huge question mark shows up on almost every table :-(

**Comment by sklages** [comment]
That's interesting .. the above description and the image have been taken from my (linux) notebook, connected via VPN. Browser is "Google Chrome".

Looking at this from work on my linux workstation, the search panel looks just fine, with a small black question mark sign close to it. Just as it should.
The sequencer status "lamps" are green little balls, one sequencer (running) with a blue "diamond" shape. "Chromium Browser" and also "Firefox 57.x", Linux.

On Windows "Google Chrome" these signs are little squares, not filled but colored, on another windows system these signs cannot be displayed (shows "01F 79C" + "28 24", "Firefox 52").

Not really a problem, but funny though ...  I will keep an eye on that :-)

**Comment by sklages** [comment]
The big sign has vanished, the other tiny optical "incorrectnesses" are not a problem. Hmm, so closed ..

**Comment by djcooke** [comment]
The giant question mark was likely caused by stale css that was cached from before the update. If you experience strange display issues like this again, try a hard refresh.

The icons on the instrument status widget have been replaced with graphics in the 0.2.108 so that they'll look consistent across all platforms.
