### ISSUE TITLE
Q: Warnings during database migration

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1343]
During database migration I always get these warnings:

```
Executing SQL callback: beforeMigrate
WARNING: DB: Trigger does not exist (SQL State: null - Error Code: 1360)
[...]
WARNING: DB: PROCEDURE miso_seqcore.addPlatform does not exist 
(SQL State: null - Error Code: 1305)
Current version of schema `miso_seqcore`: 0430
WARNING: outOfOrder mode is active. 
Migration of schema `miso_seqcore` may not be reproducible.
Schema `miso_seqcore` is up to date. No migration necessary.
Executing SQL callback: afterMigrate
WARNING: DB: FUNCTION miso_seqcore.nextval does not exist 
(SQL State: null - Error Code: 1305)
WARNING: DB: Trigger does not exist (SQL State: null - Error Code: 1360)
[...]
WARNING: DB: Unknown table 'miso_seqcore.CompletedPartitions' 
(SQL State: 42S02 - Error Code: 1051)
```
As these are just warnings it is probably nothing to worry about.
Is that something that needs fixing?

**Comment by djcooke** [comment]
These are nothing to worry about. We use SQL like `DROP PROCEDURE IF EXISTS x` and if "x" doesn't exist, MySQL throws a warning, despite the syntax suggesting that it's ok if it doesn't exist :man_shrugging: 

The "unknown table" one that looks different is the same, dropping a view that probably doesn't exist depending on what version you're migrating from

**Comment by sklages** [comment]
Ok, thanks!
