### ISSUE TITLE
runscanner-illumina : Problems compiling/deploying

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1344]
```
$ ./build-illumina-interop
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
[...]
-- Using C++11: Yes
-- Found Git: /usr/bin/git (found version "2.15.1") 
-- InterOp v1.1.1
[...]
```
Then I get a lot of warnings like this (with `make` as well):

```
metric_set.h:266:49:
 warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   metric_type &operator[](const size_t n) throw(model::index_out_of_bounds_exception)
```
and 
```
warning: unrecognized command line option ‘-Wno-eof-newline’
```

As `-Werror` is switched on it fails with an error.
When I remove `-Werror` in `InternalUtils.cmake` (what I just did for testing) it compiles just fine, but after deploying and scanning all runs show up in the **Failed** tab, not in the **Finished** tab as before.

This is version `v0.2.108`, `JsonCpp 1.8.3`. I switched back to (previously compiled & working) runscanner-illumina from version `v0.2.104`.

I cannot tell which g++ version has been used before to compile `runscanner-illumina` from version `v0.2.104` (our gcc has been updated to 7.3.0 two weeks ago).

Any ideas how to correctly deal with that issue?

**Comment by apmasell** [comment]
Unfortunately, this is all in the Illumina Interop library, not the code that's in MISO itself. I'm not really surprised that the code contains compliance errors.

We've been using GCC 5.4.0, but I've also been testing with clang, which tends to produce better error messages.

If you're on Debian/Ubuntu, you can see what GCC version you had before by doing `grep gcc /var/log/dpkg.log`. For Red Hat/Fedora, you can do `rpm -q gcc --last` to see the previous version.

I don't have access to that version of GCC, but it looks like there have been some improvements to the Illumina library itself. So, I would suggest:

* Update the Illumina library (`cd runscanner-illumina/interop; git fetch; git checkout v1.1.3`)
* Try using clang (`apt-get install clang-5.0 || yum install clang; export CXX=$(which clang++-5.0 clang++)`)

I will update the Illumina library version too.

**Comment by apmasell** [comment]
You might also want to try `cd runscanner-illumina/interop; git fetch; git checkout master; git pull` as a version. There's a more recent commit that claims to fix problems in GCC 4.4, which might be relevant?

**Comment by sklages** [comment]
I now used `master` with `g++ (GCC) 5.5.0` .. compilation now works fine out-of-the-box .. but the results are the same after deployment.
All our runs show up in `Failed` tab, `Is Configuration Good?` states `true`.

Have some requirements changed? Access to runfolders is read-only.

**Comment by apmasell** [comment]
No, that code hasn't changed. There should be a `runscanner.log` included in the Tomcat log directory. If it's failing, there should be a trace in there.

**Comment by sklages** [comment]
From the log I would say that this is the error:
```
ERROR   2018-02-22 15:02:42,579 [ForkJoinPool-1-worker-27] uk.ac.bbsrc.tgac.miso.runscanner.Scheduler  - Failed to process run: /project/solexadata/machine/SN367/170113_SN367_0019_A_HHCV5BBXX
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: java.lang.UNIXProcess$ProcessPipeInputStream@53fc0a99; line: 1, column: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3838)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2908)
	at uk.ac.bbsrc.tgac.miso.runscanner.processors.DefaultIllumina.process(DefaultIllumina.java:144)
	at uk.ac.bbsrc.tgac.miso.runscanner.Scheduler.lambda$queueDirectory$4(Scheduler.java:321)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by apmasell** [comment]
Okay. That means it's not able to start the `runscanner-illumina` binary. Try doing:

    runscanner-illumina /project/solexadata/machine/SN367/170113_SN367_0019_A_HHCV5BBXX

and seeing what the exit code is. If it exists with code 2, then the Illumina library isn't able to handle that directory. In that case, try running one of [their tools](https://github.com/Illumina/interop/releases) on that directory and see if there's a useful diagnosis.

**Comment by sklages** [comment]
The old one returns the expected data:
```
{
        "bclCount" : 112,
        "callCycle" : 310,
        "class" : "uk.ac.bbsrc.tgac.miso.dto.IlluminaNotificationDto",
        "completionDate" : "2017-01-16T01:18:23",
        "containerSerialNumber" : "HHCV5BBXX",
        "healthType" : "Completed",
        "imgCycle" : 310,
        "indexLengths" : 
        [
                8
        ],
        "laneCount" : 8,
        "metrics" : "[...]",
        "numCycles" : 310,
        "numReads" : 3,
        "pairedEndRun" : true,
        "readLength" : 151,
        "runAlias" : "170113_SN367_0019_A_HHCV5BBXX",
        "scoreCycle" : 310,
        "sequencerName" : "K00367",
        "software" : "Interop: v1.1.1 Instrument: 0",
        "startDate" : "2017-01-13T00:00:00"
}
```

The "new" ones just segfault:
`Segmentation fault`

I will have a closer look at it next week, I will also compile some Illumina tools to see if these are properly working.

**Comment by apmasell** [comment]
Well, that's exciting. If you want to send me the output from the sequencer (excluding the actual reads), I can try to debug it. You can also run it under the debugger:

```
gdb runscanner-illumina
run /project/solexadata/machine/SN367/170113_SN367_0019_A_HHCV5BBXX
```

and include the back trace here.

**Comment by sklages** [comment]
Fixed now. Seems that there was some kind of compiler version mixup.
I now used `g++ (GCC) 5.5.0` and `runscanner-illumina Interop: v1.1.3-dirty`. 
`CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` in `CMakeLists.txt` and build script were set to use our g++5 (which is not default).

```
{
    "bclCount" : 112,
    "callCycle" : 310,
    "class" : "uk.ac.bbsrc.tgac.miso.dto.IlluminaNotificationDto",
    "completionDate" : "2017-01-16T01:18:23",
    "containerSerialNumber" : "HHCV5BBXX",
    "healthType" : "Completed",
    "imgCycle" : 310,
    "indexLengths" : 
    [
        8
    ],
    "laneCount" : 8,
    "metrics" : "[<SNIP>]\n",
    "numCycles" : 310,
    "numReads" : 3,
    "pairedEndRun" : true,
    "readLength" : 151,
    "runAlias" : "170113_SN367_0019_A_HHCV5BBXX",
    "scoreCycle" : 310,
    "sequencerName" : "K00367",
    "software" : "Interop: v1.1.3-dirty Instrument: 0",
    "startDate" : "2017-01-13T00:00:00"
}
```

so, solved I assume :+1:

**Comment by sklages** [comment]
Also works with `master`:
```
"software" : "Interop: v1.1.3-3-g5ddd8d8 Instrument: 0",
```

**Comment by apmasell** [comment]
Ah, okay. It's probably that the calling conventions changed between compilers. C++ is notoriously bad at mixing code from different compilers.
