### ISSUE TITLE
Pool: Duplicate indices when a library has no index

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1371]
We sometimes create (MISO) pools, where there are unindexed libraries along with indexed ones.
In such cases **all** indices of that pool are reported as "DUPLICATE INDEX", probably because the shortest one has length 0 and as such is considered a "subsequence"  of the longer ones.

This is not a valid MISO pool, but we alter the samplesheets afterwards, before demultiplexing.

It would be much clearer if the libraries without index in a pool of indexed libraries are marked "HAS NO INDEX" .. 
Real index comparisons should be done with index lengths beyond 1 :-)

**Comment by djcooke** [comment]
I agree it would be clearer to flag these as missing indices instead of duplicates.

If some libraries in the pool are missing indices, doesn't that make it impossible to demultiplex them though? Or do you mean that the libraries are actually indexed, but that that just isn't recorded in MISO?

**Comment by sklages** [comment]
The latter; we sometimes get "ready-to-load" pools (with known indices), samples/libraries are not tracked in MISO (so we do not have index info available at this level), we just store a dummy-pool. 
Then for demultiplexing we fill in the library names and index sequences directly into the samplesheet.

**Comment by sklages** [comment]
This is implemented now.
