### ISSUE TITLE
"Instrument Status" showing just one single run in double flowcell setup

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1404]
When running two flowcells at the same time (HiSeq 2500 / 4000, NovaSeq 6000) the "Instrument Status" shows just one run, the first one. Shouldn't there be both runs displayed?
Also when clicking on the instrument field, in the popup window only one run is shown. Here should show up the second run as well.

**Comment by callunity** [comment]
We'll soon be working on fixing that widget to display both runs, but you're correct that right now it only shows the run with the most recent start date.

**Comment by djcooke** [comment]
This is addressed in https://github.com/TGAC/miso-lims/pull/1756. Instruments with multiple positions will be represented correctly in the instrument status widget once this patch is released.
