### ISSUE TITLE
Q: Naming scheme for MISO in miso.properties

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1407]
We sometimes have some issues with "wrong" samplenames, e.g. with whitespace or underscore.
This is because we still transfer sample aliases from customer-provided Excel sheets with some "by-eye-inspection".

We use the default naming scheme for MISO in `miso.properties`:
```
## ([A-z0-9]+)_S([A-z0-9]+)_(.*)
miso.naming.scheme:default
```

Would it be OK (and valid) to change the regex to something like:

```([A-z0-9]+)_S([0-9]+)_([^_\.\s]+)``` (explicitly excluding some characters)

Or probably better to `([A-z0-9]+)_S([0-9]+)_([A-Za-z0-9-]+)` (just allowing for specific characters), which should prevent "_" or "." being considered valid parts of sample aliases (at least from a "Perl point of view" :-) ).

**Comment by djcooke** [comment]
We cannot make the default validator more strict at this point, as others who already use it likely require different characters to be allowed. The naming scheme can be configured in more detail though, and you can change your configuration to make this work how you'd like. Add the following settings to your `miso.properties`:

```
miso.naming.scheme:default
miso.naming.validator.sample.alias:default
miso.naming.validator.sample.alias.regex:([A-z0-9]+)_S([0-9]+)_([A-Za-z0-9-]+)
```

For more information, configuring the naming scheme is documented in detail in the installation guide. The final table in that section lists the old naming schemes, which are outdated. I will remove that. Everything above that is accurate and complete: https://github.com/TGAC/miso-lims/blob/develop/docs/_posts/2016-01-11-installation-guide.md

**Comment by sklages** [comment]
Thanks, awesome, that's what I meant, altering regexp in `miso.properties`.

But changing the `miso.naming.validator.sample.alias.regex` now will hopefully not have any side effects with old sample or lib aliases containing some "forbidden" characters? 

I will have a look..

**Comment by djcooke** [comment]
Closing as the question has been answered. Feel free to reopen or create a new ticket if there is a remaining/related issue
