### ISSUE TITLE
Cannot save changes to libraries propagated from samples

### ISSUE THREAD

**Issue by jxshi** [TGAC/miso-lims#1409]
We have recently deployed MISO-LIMS in our lab. It is indeed an awesome software. I was trying to walk through the tutorial to check out how to use it. However, when I propagated libraries from samples, I was not able to save to changes to the libraries due to the following errors:
```
Oh snap!
The following rows failed to save:

Please fix highlighted cells.
```
And in this case, "Platform" was highlighted. I have tried to put "Illumina" or "ILLUMINA" or "illumina", it seems that "Illumina" should be the right form in this case. But it won't let me save the changes. Can you check this out for me please?
Thank you in advance!

**Comment by callunity** [comment]
Hi @jxshi ,
Could you please send us a screenshot of the entire row you were trying to save so we can investigate?
Also, when you click on a cell in the "Platform" column, what are the options visible in the dropdown menu?
Thanks!

**Comment by jxshi** [comment]
Here is a screen shot of the error message and the context that I filled in the table. Though there is a dropdown menu under ‘Platform’ column, nothing pops up when i click it or keep the mouse stays in the box.

Thank you for you help!
[cid:BA497771-D1D4-4C8C-BC3C-80D02427032B@lan]
On Apr 19, 2018, at 9:54 PM, Heather Armstrong <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @jxshi<https://github.com/jxshi> ,
Could you please send us a screenshot of the entire row you were trying to save so we can investigate?
Also, when you click on a cell in the "Platform" column, what are the options visible in the dropdown menu?
Thanks!

**Comment by jxshi** [comment]
![Uploading ScreenShot.png…]()

**Comment by callunity** [comment]
@jxshi do you have any active sequencers added to MISO? The Platform list is constrained to platforms with available sequencers. I can see how that's not obvious though, and will fix that for the next release of MISO. In the meantime, please add an Illumina sequencer via the "Instruments" menu option, and you should be able to create libraries. Please let me know if you run into any more issues!

**Comment by jxshi** [comment]
Awesome! That works. 

Thank you!
