### ISSUE TITLE
Q: Starting MISO problem

### ISSUE THREAD

**Issue by passanger** [TGAC/miso-lims#1421]
Hi, 
I've tried to start newest version of the MISO locally on my machine by [instruction](https://github.com/TGAC/miso-lims/blob/develop/docs/_posts/2016-01-11-installation-guide.md)
Problem is that MISO trying read classes from configuration that doesn't exits.

`26-Apr-2018 13:24:50.216 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [uk.ac.bbsrc.tgac.miso.webapp.context.MisoAppListener]
 org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [uk.ac.bbsrc.tgac.miso.persistence.impl.HibernateSequencerReferenceDao]; nested exception is java.io.FileNotFoundException: class path resource [uk/ac/bbsrc/tgac/miso/core/store/SequencerReferenceStore.class] cannot be opened because it does not exist`

As i can see these classes were deleted, but MISO still trying to find them. Also i can't find, in any configuration files, anything about these classes in the newest version.
Please note that i was able to start locally v0.2.105 version by instructions.
Can some one help me?

Thank you

**Comment by djcooke** [comment]
Is it possible that there are remnants of a previous version somewhere? Did you delete both the `.../webapps/ROOT` directory and `.../webapps/ROOT.war` before attempting to deploy a new version?

**Comment by callunity** [comment]
@passanger that's very strange. Could you please paste here the exact commands you used to clear out the last version and deploy the new version?

**Comment by passanger** [comment]
Hi @callunity,
Yes, of course.
Step by step:
```
1.  mvn clean package -P external (inside of miso src folder)
2. delete ROOT.jar and ROOT folder from /Users/Passanger/Documents/programming/tools/tomcat8/webapps/
3. copy .../miso-web/target/ROOT.war to .../tomcat8/webapps/
4. db migration 
rm -f lib/sqlstore-*.jar
unzip -xjo /Users/Passanger/Documents/programming/tools/tomcat8/webapps/ROOT.war 'WEB-INF/lib/sqlstore-*.jar' -d lib
./flyway -user=root -password=******** -url=jdbc:mysql://localhost:3306/lims -outOfOrder=true -locations=classpath:db/migration,classpath:uk.ac.bbsrc.tgac.miso.db.migration migrate
5.  start tomcat  ./startup.sh  (in  /Users/Passanger/Documents/programming/tools/tomcat8/bin

```

**Comment by callunity** [comment]
Just to confirm - are you deleting a `ROOT.jar` or a `ROOT.war` file in step 2?
And at which step do you stop Tomcat?

**Comment by passanger** [comment]
Yes am deleting ROOT.war.
I delete `ROOT.war` and `ROOT folder` , when i start `mvn clean package -P external` (step 1)

**Comment by callunity** [comment]
And at what step do you stop Tomcat? (`.../tomcat8/bin/shutdown.sh` or similar) Or do you just run `startup.sh` to restart Tomcat without stopping it explicitly?

**Comment by passanger** [comment]
Im stoping tomcat manually `.../tomcat8/bin/shutdown.sh`

**Comment by callunity** [comment]
And at what step do you do so?

**Comment by passanger** [comment]
after step 1

**Comment by passanger** [comment]
i've successfully started miso
