### ISSUE TITLE
Q: Is the latest tag safe to be installed?

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1431]
I am referring to tags `v0.2.116 to v0.2.118`. Not sure if these could be safely installed or if I should wait for the next "latest release". I am currently running `v0.2.115`.

**Comment by apmasell** [comment]
Sorry, there's been some confusion on our end. The latest tag is what we use internally and it *should* work, but there might be bugs. We use it internally for a week and if we find no major faults, then we mark it as good. v0.2.116 is definitely bad. v0.2.117 is good, but I was confused and thought it wasn't. I'm marking it as released now. You can try to v0.2.118, but no guarantees.

**Comment by apmasell** [comment]
v0.2.117 is now marked as good.
