### ISSUE TITLE
0.2.117 : db migration issue

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1433]
I just wanted to update our MISO instance and ran into the following error:

```
Migration V0480__auto_main.sql failed
-------------------------------------
SQL State  : 22004
Error Code : 1138
Message    : Invalid use of NULL value
Location   : db/migration/V0480__auto_main.sql (<snip path>)
Line       : 81
Statement  : ALTER TABLE SequencerPartitionContainer MODIFY COLUMN sequencingContainerModelId bigint(20) NOT NULL
```
When I look into the database **after** that error, I do see the problem: There are a handful of flowcells having a `NULL` value in column `sequencingContainerModelId`.  I reverted back to `115` and could not fix these columns as it seems that these are introduced by the current update (117).

So what do I need to fix in `115` database that the update `117` will be successful? :smiley:

**Comment by djcooke** [comment]
Previously, the number of partitions that were valid for a sequencing container were determined by the `PlatformSizes` database table. This has now been replaced by Sequencing Container Models, which define the actual container (flow cell, etc.) type that is used. A number of known Illumina flow cell models were added.

In addition, "unknown" models were added for any value in the `PlatformSizes` table. For example, if `PlatformSizes` contained a record of 8 partitions allowed for an Illumina platform, then an "Unknown 8-lane Illumina Flow Cell" would be created. These "Unknown" models are to be used as a fall-back when the actual model cannot be determined.

I'm guessing that your migration is failing because there are containers in your database that have an invalid number of partitions associated with them. Try this to identify the problem containers:

```
SELECT sub.containerId, sub.platform, sub.partitions
FROM (
  SELECT spc.containerId, spc.platform, COUNT(spcp.partitions_partitionId) AS partitions
  FROM SequencerPartitionContainer spc
  JOIN SequencerPartitionContainer_Partition spcp ON spcp.container_containerId = spc.containerId
  GROUP BY spc.containerId
) sub
LEFT JOIN PartitionSizes ps ON ps.platform_platformId = sub.platform AND ps.partitionSize = sub.partitions
WHERE ps.partitionSize IS NULL;
```

The fix will then be one of two things

1. add a `PlatformSizes` record that indicates the number of partitions is valid for the container's platform
2. add/delete records in the `_Partition` and `SequencerPartitionContainer_Partition` tables to correct the invalid data

**Comment by sklages** [comment]
Thanks, I will try as as soon as possible and report back. 
In your above code is a little typo:
```
LEFT JOIN PartitionSizes ps ON <..>
```
should read:
```
LEFT JOIN PlatformSizes ps ON <...>
```

**Comment by sklages** [comment]
The Changes for `0.2.117` and `0.2.118` look the same. What are the differences? Is it safe to update directly to `0.2.118` (from `0.2.115`)?

**Comment by callunity** [comment]
I've updated the changes for `0.2.117`. If you've fixed the invalid data in your database, it should be fine to update directly to 0.2.118.

**Comment by sklages** [comment]
Hmm, I'd simply like to delete these partition containers/partitions ... these are just a few which can be easily re-assigned (some of them are simply empty).
Deleting from `SequencerPartitionContainer_Partition` works, deleting from `_Partition` is problematic, e.g.:
```
Operation failed: There was an error while applying the SQL script to the database.
Executing:
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='425';

ERROR 1451: 1451: Cannot delete or update a parent row: a foreign key constraint fails (`miso_seqcore`.`SequencerPartitionContainer_Partition`, CONSTRAINT `spcp_partition_partitionid_fk` FOREIGN KEY (`partitions_partitionId`) REFERENCES `_Partition` (`partitionId`))
SQL Statement:
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='425'
```

**Comment by callunity** [comment]
The foreign key constraint that's failing is on `SequencerPartitionContainer_Partition`. There's definitely no entry in that table for partitionId 425?

**Comment by sklages** [comment]
Just to be sure that I didn't got you both wrong. Using the aforementioned SQL query I get some records, exactly 11. One example:
```
containerId  platform partitions
70           3            1
```

That's a NextSeq container with just one lane/partition.

The record in `SequencerPartitionContainer_Partition` looks like:
```
container_containerId  partitions_partitionId
      70                         425
```
The corresponding part in `_Partition`:
```
partitionId   partitionNumber   pool_poolId
   425               1             <NULL>
```
I completely wanted to delete both entries. So probably I got the "keywords" wrong?
All these 11 sequencing containers can be removed; I can re-create them if necessary.

**Comment by callunity** [comment]
I should have clarified - when you said "Deleting from SequencerPartitionContainer_Partition works, deleting from _Partition is problematic" did you do the deletes in that order? The error message you posted seems to indicate that deleting from SequencerPartitionContainer_Partition didn't work, at least not for the row with partitionId = 425.

**Comment by sklages** [comment]
Hmm, with that record it worked now with the `SequencerPartitionContainer_Partition` -> `_Partition` deletion order. That was just one record. I probably did it wrong.

But the next one is more than record and it fails in the correct order:
```
containerId  platform partitions
234         3       8
```
Again a NextSeq run, here with 8 partitions. I first deleted four partitions from `SequencerPartitionContainer_Partition` and tried to delete the corresponding partitions from `_Partition`.
With the above error. Then I deleted the other four entries in `SequencerPartitionContainer_Partition` and tried to delete all eight partitions in `_Partition`.

```
Operation failed: There was an error while applying the SQL script to the database.
Executing:
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1444';
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1445';
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1446';
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1447';
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1440';
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1441';
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1442';
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1443';

ERROR 1451: 1451: Cannot delete or update a parent row: a foreign key constraint fails (`miso_seqcore`.`SequencerPartitionContainer_Partition`, CONSTRAINT `spcp_partition_partitionid_fk` FOREIGN KEY (`partitions_partitionId`) REFERENCES `_Partition` (`partitionId`))
SQL Statement:
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1444'

ERROR 1451: 1451: Cannot delete or update a parent row: a foreign key constraint fails (`miso_seqcore`.`SequencerPartitionContainer_Partition`, CONSTRAINT `spcp_partition_partitionid_fk` FOREIGN KEY (`partitions_partitionId`) REFERENCES `_Partition` (`partitionId`))
SQL Statement:
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1445'

ERROR 1451: 1451: Cannot delete or update a parent row: a foreign key constraint fails (`miso_seqcore`.`SequencerPartitionContainer_Partition`, CONSTRAINT `spcp_partition_partitionid_fk` FOREIGN KEY (`partitions_partitionId`) REFERENCES `_Partition` (`partitionId`))
SQL Statement:
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1446'

ERROR 1451: 1451: Cannot delete or update a parent row: a foreign key constraint fails (`miso_seqcore`.`SequencerPartitionContainer_Partition`, CONSTRAINT `spcp_partition_partitionid_fk` FOREIGN KEY (`partitions_partitionId`) REFERENCES `_Partition` (`partitionId`))
SQL Statement:
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1447'

ERROR 1451: 1451: Cannot delete or update a parent row: a foreign key constraint fails (`miso_seqcore`.`SequencerPartitionContainer_Partition`, CONSTRAINT `spcp_partition_partitionid_fk` FOREIGN KEY (`partitions_partitionId`) REFERENCES `_Partition` (`partitionId`))
SQL Statement:
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1440'

ERROR 1451: 1451: Cannot delete or update a parent row: a foreign key constraint fails (`miso_seqcore`.`SequencerPartitionContainer_Partition`, CONSTRAINT `spcp_partition_partitionid_fk` FOREIGN KEY (`partitions_partitionId`) REFERENCES `_Partition` (`partitionId`))
SQL Statement:
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1441'

ERROR 1451: 1451: Cannot delete or update a parent row: a foreign key constraint fails (`miso_seqcore`.`SequencerPartitionContainer_Partition`, CONSTRAINT `spcp_partition_partitionid_fk` FOREIGN KEY (`partitions_partitionId`) REFERENCES `_Partition` (`partitionId`))
SQL Statement:
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1442'

ERROR 1451: 1451: Cannot delete or update a parent row: a foreign key constraint fails (`miso_seqcore`.`SequencerPartitionContainer_Partition`, CONSTRAINT `spcp_partition_partitionid_fk` FOREIGN KEY (`partitions_partitionId`) REFERENCES `_Partition` (`partitionId`))
SQL Statement:
DELETE FROM `miso_seqcore`.`_Partition` WHERE `partitionId`='1443'
```
So usually you are right so that I must do something here.

**Comment by callunity** [comment]
Could you please post the commands you used for deleting from both `SequencerPartitionContainer_Partition` and `_Partition`?

**Comment by callunity** [comment]
Out of curiosity, what is the output of the following?
```
SELECT * FROM SequencerPartitionContainer_Partition WHERE partitions_partitionId IN (1440,1441,1442,1443,1444,1445,1446,1447);
```

**Comment by sklages** [comment]
OK, that looks interesting:
```
mysql> SELECT * FROM SequencerPartitionContainer_Partition WHERE partitions_partitionId IN (1440,1441,1442,1443,1444,1445,1446,1447);
+-----------------------+------------------------+
| container_containerId | partitions_partitionId |
+-----------------------+------------------------+
|                   234 |                   1440 |
|                   235 |                   1440 |
|                   234 |                   1441 |
|                   235 |                   1441 |
|                   234 |                   1442 |
|                   235 |                   1442 |
|                   234 |                   1443 |
|                   235 |                   1443 |
|                   234 |                   1444 |
|                   235 |                   1444 |
|                   234 |                   1445 |
|                   235 |                   1445 |
|                   234 |                   1446 |
|                   235 |                   1446 |
|                   234 |                   1447 |
|                   235 |                   1447 |
+-----------------------+------------------------+
```

Again, an old run from old MISO (without NextSeq support).

**Comment by callunity** [comment]
Yes, that would explain it! Once you fix those, migration will work (hopefully!).

**Comment by sklages** [comment]
Well I fixed all eleven fishy containers and the query provided by @djcooke [here](https://github.com/TGAC/miso-lims/issues/1433#issuecomment-387084233) now returns an empty result set, nothing.

Running `0.2.117` migration still results in exactly the same error:
```
ERROR: Migration of schema `miso_seqcore` to version 0480 failed! Please restore backups and roll back database and code!
ERROR: 
Migration V0480__auto_main.sql failed
-------------------------------------
SQL State  : 22004
Error Code : 1138
Message    : Invalid use of NULL value
Location   : db/migration/V0480__auto_main.sql (/project/miso/2018/build_tools/flyway/3.2.1/file:/project/miso/2018/build_tools/flyway/3.2.1/lib/sqlstore-0.2.117.jar!/db/migration/V0480__auto_main.sql)
Line       : 81
Statement  : ALTER TABLE SequencerPartitionContainer MODIFY COLUMN sequencingContainerModelId bigint(20) NOT NULL
```
I am confused :grey_question: 

Any idea how to continue?

**Comment by callunity** [comment]
Hi @sklages I suspect that the `PartitionSizes` table is missing one or more container configurations after you fixed the fishy containers. After you fixed the containers, did you run the SELECT statement and updates to `PartitionSizes` from [djcooke's initial reply to this issue](https://github.com/TGAC/miso-lims/issues/1433#issuecomment-387084233)?

**Comment by sklages** [comment]
Sure, that's what I did. It returns no records anymore. 
At the very beginning, before fixing, there were 11 records returned. Some of those I simply deleted in `SequencerPartitionContainer_Partition`, some of those I fixed to contain correct patitions and partition numbers.

There must be still something wrong (probably with some NextSeq related stuff) which is not catched by the aforementioned sql query ...

**Comment by djcooke** [comment]
You could check which containers have null models after the migration fails:

```
SELECT spc.*, COUNT(*) AS partitions
FROM SequencerPartitionContainer spc
LEFT JOIN SequencerPartitionContainer_Partition spcp ON spcp.container_containerId = spc.containerId
GROUP BY spc.containerId
WHERE sequencingContainerModelId IS NULL;
```

**Comment by djcooke** [comment]
I think my original query would have missed containers that have 0 partitions associated with them too. Here's a fix that should include them:

```
SELECT sub.containerId, sub.platform, sub.partitions
FROM (
  SELECT spc.containerId, spc.platform, COUNT(spcp.partitions_partitionId) AS partitions
  FROM SequencerPartitionContainer spc
  LEFT JOIN SequencerPartitionContainer_Partition spcp ON spcp.container_containerId = spc.containerId
  GROUP BY spc.containerId
) sub
LEFT JOIN PlatformSizes ps ON ps.platform_platformId = sub.platform AND ps.partitionSize = sub.partitions
WHERE ps.partitionSize IS NULL;
```

**Comment by sklages** [comment]
ok, I see.

With your query I get three records, all of these from my "fishy elevens". These were the records which I simply deleted in `SequencerPartitionContainer_Partition`. I don't need these .. 

How can I fix (=remove) these records in question?

**Comment by djcooke** [comment]
If you deleted the records from `SequencerPartitionContainer_Partition`, you should also delete the matching records in `_Partition` and `SequencerPartitionContainer`. The easiest way to do this would be using the containerId:

```
SET @containerId = 1234; -- replace 1234 with the actual container ID

DELETE FROM _Partition WHERE partitionId IN (
  SELECT partitions_partitionId FROM SequencerPartitionContainer_Partition
  WHERE container_containerId = @containerId
);
DELETE FROM SequencerPartitionContainer_Partition WHERE container_containerId = @containerId;
DELETE FROM SequencerPartitionContainer WHERE containerId = @containerId;
```

**Comment by sklages** [comment]
The `DELETE`s from `_Partition` and `SequencerPartitionContainer_Partition` do work (I tested only with the first of the three suspect containers, ID=70). 
The last `DELETE` threw an error: 

```
07:39:24    DELETE FROM SequencerPartitionContainer WHERE containerId = @containerId    Error Code: 1451. Cannot delete or update a parent row: a foreign key constraint fails (`miso_seqcore`.`Run_SequencerPartitionContainer`, CONSTRAINT `Run_SequencerPartitionContainer_ibfk_2` FOREIGN KEY (`containers_containerId`) REFERENCES `SequencerPartitionContainer` (`containe)   0.050 sec
```
I did not try with the other ones. I restored database ...

**Comment by djcooke** [comment]
That means the container you're deleting is attached to a run. If you're sure you want to be deleting this, you can remove the container from the run with

```
DELETE FROM Run_SequencerPartitionContainer WHERE containers_containerId = @containerId;
```

(before deleting from `SequencerPartitionContainer`)

**Comment by sklages** [comment]
hmm, .. this "old-miso-old-miseq500-flowcells"-heritage is quite laborious ... :worried: 
Now I did:
```
SET @containerId = 70;

DELETE FROM _Partition WHERE partitionId IN (
  SELECT partitions_partitionId FROM SequencerPartitionContainer_Partition
  WHERE container_containerId = @containerId
);
DELETE FROM SequencerPartitionContainer_Partition WHERE container_containerId = @containerId;
DELETE FROM Run_SequencerPartitionContainer WHERE containers_containerId = @containerId;
DELETE FROM SequencerPartitionContainer WHERE containerId = @containerId;
```
This still results in an error, now concerning the change log:
```
06:36:19    DELETE FROM SequencerPartitionContainer WHERE containerId = @containerId    Error Code: 1451. Cannot delete or update a parent row: a foreign key constraint fails (`miso_seqcore`.`SequencerPartitionContainerChangeLog`, CONSTRAINT `fk_containerChangeLog_box` FOREIGN KEY (`containerId`) REFERENCES `SequencerPartitionContainer` (`containerId`)) 0.018 sec
```
Database restored ..

**Comment by djcooke** [comment]
Ah, right. Need to delete the change logs too. Try this:

```
SET @containerId = 70;

DELETE FROM _Partition WHERE partitionId IN (
  SELECT partitions_partitionId FROM SequencerPartitionContainer_Partition
  WHERE container_containerId = @containerId
);
DELETE FROM SequencerPartitionContainer_Partition WHERE container_containerId = @containerId;
DELETE FROM Run_SequencerPartitionContainer WHERE containers_containerId = @containerId;
DELETE FROM SequencerPartitionContainerChangeLog WHERE containerId = @containerId;
DELETE FROM SequencerPartitionContainer WHERE containerId = @containerId;
```

**Comment by sklages** [comment]
Yes, it works like a charm. I now was able to update `0.2.115->0.2.117->0.2.118->0.2.119->0.2.120` without any issues.

Thanks!
