### ISSUE TITLE
Missing added instrument for pool order creation

### ISSUE THREAD

**Issue by passanger** [TGAC/miso-lims#1449]
Hi,
I'm not able to create pool oder with new added instrument.
This is happening for every new added instrument, after few "empty cache and hard reload"  and restarts, new instrument appears in create pool oder dialogs.
I think this is related to `constant.js` which is loaded only once
`  <script type="text/javascript" src="<c:url value='/miso/constants.js'/>?ts=<fmt:formatNumber value="${timestamp.time / 60000}" maxFractionDigits="0" groupingUsed="false" />"></script>` (`header.jsp`)

Do I do something wrong or this is an issue?

Thanks,
Marko

**Comment by djcooke** [comment]
The values in `constants.js` are updated every 15 minutes, so you may have to wait up to 15 minutes after adding a new instrument for it to show up everywhere

**Comment by passanger** [comment]
Thank you djcooke.
I'll close ticket.
