### ISSUE TITLE
Q: Increase time before auto logout

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1485]
Where can I set the time for MISO to log out the current user while not being active?
This is too short for us :-)

**Comment by callunity** [comment]
How many minutes were you thinking of changing it to?

**Comment by callunity** [comment]
If it's to a time frame that our group is happy with, we'd make the change directly in the repo. If our lab's hopes end up being different from yours, here is the line you'd change (`<session-timeout>` is in minutes): https://github.com/TGAC/miso-lims/blob/develop/miso-web/src/main/webapp/WEB-INF/web.xml#L187

**Comment by sklages** [comment]
Hmm, a few hours I think. From now one hour to maybe four or six hours?

**Comment by callunity** [comment]
Hi @sklages ,
Our lab has elected to keep the current timeout, so you'll want to update your web.xml as part of your release process.
