### ISSUE TITLE
v0.2.136: Column 'creator' cannot be null

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1631]
Updating `v0.2.134` to `v0.2.136` I got an error during migration:
```
ERROR: Migration of schema `miso_seqcore` to version 0620 failed! Please restore backups and roll back database and code!
ERROR: 
Migration V0620__auto_main.sql failed
-------------------------------------
SQL State  : 23000
Error Code : 1048
Message    : Column 'creator' cannot be null
Location   : db/migration/V0620__auto_main.sql (/path/to/flyway/3.2.1/file:/path/to/flyway/3.2.1/lib/sqlstore-0.2.136.jar!/db/migration/V0620__auto_main.sql)
Line       : 31
Statement  : UPDATE LibraryDilution SET creator = (SELECT userId FROM User WHERE fullName = dilutionUserName)
```
What is the problem here?

**Comment by djcooke** [comment]
You have one or more dilution users that don't actually exist in MISO. This field used to store the username, and we've updated it to instead store the user ID. You can find the missing users using this query:

```
SELECT dilutionUserName FROM LibraryDilution WHERE dilutionUserName NOT IN (SELECT loginName FROM User);
```

Either correct these to match existing loginNames, or create new users using the missing loginNames. You can set these new users as inactive to prevent them from logging in.

**Comment by sklages** [comment]
Hmm, ok. my `loginName` is `klages`. Using your query I would be listed as `Sven Klages` (the `dilutionUserName` is obviously  `fullName` from `User`).

In the error message, `SELECT userId FROM User WHERE fullName = dilutionUserName` compares full name `Sven Klages` to `Sven Klages` (MISO after migration from old database scheme) or to `klages` (old MISO migrated data). <br />
`dilutionUserName` has changed from `loginName` (old MISO) to `fullName` (new MISO).

Your query returns some 1600 results, all showing the `fullName` of the lab staff, all existent, for all dilutions after our MISO migration at the beginning of this year.

In your query you are looking for `dilutionUserName` not present as  `loginName` in `User` table, actually if "Sven Klages" is present table `User` as `loginName=Sven Klages` (which isn't as loginName is `klages`).

hmm, I am a bit puzzled. Do you get what I mean?

**Comment by djcooke** [comment]
Ah, sorry. I had the wrong field. Try this instead:

```
SELECT dilutionUserName FROM LibraryDilution WHERE dilutionUserName NOT IN (SELECT fullName FROM User);
```

**Comment by sklages** [comment]
So basically these are **all entries from pre-migrated MISO database** where `dilutionUserName` equaled to `loginName`.  I would need to change e.g. `dilutionUserName=klages` (loginName) to `dilutionUserName=Sven Klages` (fullName). Is that correct?

Do you have a SQL query at hand? :sweat_smile:

**Comment by djcooke** [comment]
Yes, each `dilutionUserName`s must be the `fullName` of an existing user. You could use this query to change `loginName`s to `fullName`s:

```
UPDATE LibraryDilution d
JOIN User u ON u.loginName = d.dilutionUserName
SET dilutionUserName = u.fullName
WHERE u.fullName IS NOT NULL;
```

**Comment by sklages** [comment]
Worked like a charm, as usual :+1: Thanks.
