### ISSUE TITLE
Q: v0.2.136 -> miso.run.report.links

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1640]
I read
> CONFIG CHANGE: External service links can be added to Run pages. This can be configured in miso.properties with the property miso.run.report.links

Can you explain? Where do I find some documentation? Can you give an example for such "external service link"?

**Comment by djcooke** [comment]
We actually documented this better within the `miso.properties` file where it's configured, but I suppose it would be better to include the full documentation in the release notes as well since you may have no other reason to ever look at the `miso.properties` that's included in the `miso-web` module. We'll make that change and be sure to detail config changes in the release notes in the future. For now, here's the full documentation:

```
## config for links to external Run report services.
## format: <PlatformType>|<link text>|<URI with placeholders>
## PlatformTypes can be comma-separated in the first field
## placeholders can be any of {id}, {name}, {alias}.
## multiple report links can be double-backslash-separated (\\).
#miso.run.report.links:Illumina,PacBio|External Run Link|http://example.com/{id}
```

**Comment by sklages** [comment]
ok, .. that's the formal description. But honestly, I still have no clue of the purpose. What would "http://example.com/{id}" deliver? Where would such "external Run report services" show up in MISO?
What is "report" here actually referring to?

**Comment by callunity** [comment]
Suppose your institute's pipeline generates a report for each run that contains extra QC info, and you want to easily link out to the run's additional QC info from the Edit Run page. If this QC report has a predictable URL that only varies by swapping in each run's alias, you could use this feature. When you load the Edit Run page, MISO will generate the URL to the particular run's report (it replaces the placeholder value with the relevant run attribute value). Does that make more sense?

**Comment by sklages** [comment]
Perfectly, thanks :-) We currently attach our run report to the run. But that would be a smart and more flexible alternative .. I'll have a look..
