### ISSUE TITLE
mvn flyway:clean fails on develop branch

### ISSUE THREAD

**Issue by tolot27** [TGAC/miso-lims#1669]
I've checkout the develop branch (HEAD defaults to it) and build miso. That worked great. Unfortunately, I was not able to initialize a new database using flyway command line. Then I found `mvn flyway:clean flyway:migrate`, which is not mentioned by the docs BTW. This maven build also fails, but on fetching the SNAPSHOT from the tgac-repo. Probably, it is not there because it is the current build. The error is:

```
/mnt/soft/miso-lims/sqlstore$ mvn flyway:clean
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building MISO SQL Store 0.2.143-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading from tgac-repo: http://repos.tgac.ac.uk/maven/repo/uk/ac/bbsrc/tgac/miso/core/0.2.143-SNAPSHOT/maven-metadata.xml
Downloading from tgac-repo: http://repos.tgac.ac.uk/maven/repo/uk/ac/bbsrc/tgac/miso/core/0.2.143-SNAPSHOT/core-0.2.143-SNAPSHOT.pom
[WARNING] The POM for uk.ac.bbsrc.tgac.miso:core:jar:0.2.143-SNAPSHOT is missing, no dependency information available
Downloading from tgac-repo: http://repos.tgac.ac.uk/maven/repo/uk/ac/bbsrc/tgac/miso/core/0.2.143-SNAPSHOT/core-0.2.143-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.616 s
[INFO] Finished at: 2018-09-19T13:37:22+02:00
[INFO] Final Memory: 15M/180M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sqlstore: Could not resolve dependencies for project uk.ac.bbsrc.tgac.miso:sqlstore:jar:0.2.143-SNAPSHOT: Could not find artifact uk.ac.bbsrc.tgac.miso:core:jar:0.2.143-SNAPSHOT in tgac-repo (http://repos.tgac.ac.uk/maven/repo) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```
How to use it with dev branch?

**Comment by tolot27** [comment]
After switching to the master branch, build it again, it works. Hence, there is some problem with the SNAPSHOT. Maven should look up the snapshot files locally.

**Comment by djcooke** [comment]
If using the Flyway command-line tool as recommended in the install guide, you must ensure that you are using version 3.2.1 of the command-line tool, as documented. Flyway has made some breaking changes since then, and later versions will not likely work with MISO.

If using the Maven Flyway Plugin, Maven will use snapshots from your local repository. The Maven Flyway Plugin will need to run from the `sqlstore` module, however, which depends on other MISO modules. This means that you need to build the entire MISO project first:

```
cd miso-lims
mvn clean install -P external
cd sqlstore
mvn flyway:clean
mvn flyway:migrate
```

**Comment by tolot27** [comment]
Thats all what I did. I've used `flyway-commandline-3.2.1.tar.gz` and also built the entire miso-lims; exactly as you described. With the master branch, `mvn flyway:...` works, but not with the develop branch.

**Comment by tolot27** [comment]
flyway command line also fails with master (v0.2.141):

```
Migrating schema `miso` to version 0611 - Attachments
Sep 19, 2018 3:51:31 PM uk.ac.bbsrc.tgac.miso.db.migration.V0611__Attachments migrate
INFORMATION: Scanning existing attachments to save in database...
ERROR: Migration of schema `miso` to version 0611 failed! Please restore backups and roll back database and code!
ERROR: Migration failed !
```
As long as `mvn flyway:...` works with the release, I'm happy.

**Comment by djcooke** [comment]
I just now did this and it worked fine:

```
cd miso-lims
git checkout develop
git pull
mvn clean install -P external
cd sqlstore
mvn flyway:clean
mvn flyway:migrate
```
develop branch HEAD is currently at b5d7721 Minor code cleanup (#1667)

The error you posted with the Maven Flyway Plugin was that `miso-core` couldn't be found. If you have successfully built the entire MISO project using `mvn clean install -P external`, that means that `sqlstore` has been built successfully, which means that the `miso-core` dependency was satisfied. I'm not sure how you could get that error after the full project build was successful.

Did the Flyway command-line tool provide any more output on the failed run? Based on the log you posted, my only guess is that `filesDir` was missing or invalid. What was the exact command line you used (please omit your username/password)?

**Comment by tolot27** [comment]
The problem with flyway command line was most likely a file permission problem. I had trouble starting the ROOT.war. After executing `sudo chown -R tomcat:tomcat /storage/miso` everything works, also flyway command line.

**Comment by tolot27** [comment]
After switching to dev branch (83d90e65b) the problem appeared again. Then doing:

```
git pull
...
83d90e65b..b5d77210a  develop
...
mvn clean package -P external 
cd sqlstore
mvn flyway:clean
fmg@itmgn:/mnt/soft/miso-lims/sqlstore$ mvn flyway:clean
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building MISO SQL Store 0.2.143-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading from tgac-repo: http://repos.tgac.ac.uk/maven/repo/uk/ac/bbsrc/tgac/miso/core/0.2.143-SNAPSHOT/maven-metadata.xml
Downloading from tgac-repo: http://repos.tgac.ac.uk/maven/repo/uk/ac/bbsrc/tgac/miso/core/0.2.143-SNAPSHOT/core-0.2.143-SNAPSHOT.pom
[WARNING] The POM for uk.ac.bbsrc.tgac.miso:core:jar:0.2.143-SNAPSHOT is missing, no dependency information available
Downloading from tgac-repo: http://repos.tgac.ac.uk/maven/repo/uk/ac/bbsrc/tgac/miso/core/0.2.143-SNAPSHOT/core-0.2.143-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.474 s
[INFO] Finished at: 2018-09-19T18:02:25+02:00
[INFO] Final Memory: 15M/181M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sqlstore: Could not resolve dependencies for project uk.ac.bbsrc.tgac.miso:sqlstore:jar:0.2.143-SNAPSHOT: Could not find artifact uk.ac.bbsrc.tgac.miso:core:jar:0.2.143-SNAPSHOT in tgac-repo (http://repos.tgac.ac.uk/maven/repo) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by callunity** [comment]
Running `mvn clean package -P external` means it isn't being installed locally, which is why Maven is then trying to find it in `tgac-repo`. Can you try @djcooke 's suggestion and run `mvn clean install -P external` instead? That should install the project to your local Maven folder, so Maven will find that first and won't have to go searching in `tgac-repo`.

**Comment by tolot27** [comment]
Sorry, my oversight. Indeed, `install` instead of `package` did the trick. It is good to know how to build based on dev branch because I plan some adaptions.

**Comment by callunity** [comment]
Glad to hear it worked!
