### ISSUE TITLE
issus 

### ISSUE THREAD

**Issue by eunhaejo** [TGAC/miso-lims#1725]
i download demo version of miso-lims using docker.
i tried to add one sample  but it doesn't working.

whatever i input in Alias, it repeat this error..

alias must match the pattern: ([A-z0-9]+)_S([A-z0-9]+)_(.*)

english, number, special character, anything works.

**Comment by djcooke** [comment]
This is the default regex pattern for sample alias validation. The pattern can be changed via configuration in MISO, though it cannot be changed on demo version.

This regex means that the alias must begin with a series of letters and/or numbers, followed by a capital 'S', followed by another series of letters and/or numbers, followed by anything

**Comment by djcooke** [comment]
Closing issue as the error was explained and there has been no further activity here.
