### ISSUE TITLE
Docs broken?

### ISSUE THREAD

**Issue by brainstorm** [TGAC/miso-lims#1728]
From point 9 onwards on the [(new) user manual](http://tgac.github.io/miso-lims/usr/user-manual-v2.html), pretty much all links are 404'd?

I.e: http://tgac.github.io/miso-lims/user_manual/library_dilutions.html

**Comment by djcooke** [comment]
Thanks for reporting this. We are currently in the process of writing the new user manual, though I realize now that's not very obvious. I will add a note about that to the top of the table of contents. In the meantime, if you have any questions about undocumented or poorly documented features, please feel free to ask
