### ISSUE TITLE
Q: Attachment Category

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1757]
How are the "attachment categories" supposed to be expanded?

When I attach a file to a run, I can only select "Misc." from the categories dropdown menu. 

I haven't found anything in the GUI and stored procedures to expand the categories.  I do see a table "AttachmentCategory" in the database which is currently empty. Is it enough to fill this table with different categories?

**Comment by djcooke** [comment]
You could add them in the database directly, but there is an Attachment Categories page in the MISO UI where you can add new categories too. It's under Institute Defaults in the menu

**Comment by djcooke** [comment]
I'm talking about the navigation menu on the left side of the screen:

<img width="218" alt="screen shot 2018-11-21 at 10 29 01 am" src="https://user-images.githubusercontent.com/12240540/48851167-6029a300-ed78-11e8-9152-63819c821c7e.png">

**Comment by djcooke** [comment]
Ah... I just realized the Institute Defaults section only appears in detailed sample mode, while attachment categories are not specific to detailed sample mode. We'll fix that, but in the meantime, you can still get to the page by its url: `.../miso/attachmentcategories/list`

**Comment by djcooke** [comment]
Fixed in https://github.com/TGAC/miso-lims/pull/1758. QC Types link was also missing
