### ISSUE TITLE
How do I cite Miso?

### ISSUE THREAD

**Issue by jsmedmar** [TGAC/miso-lims#1759]
How do I cite Miso?How do I cite Miso?

**Comment by morgantaschuk** [comment]
Hi @jsmedmar , you can cite MISO LIMS using the Zenodo DOI [10.5281/zenodo.1492883](https://doi.org/10.5281/zenodo.1492883). For example, using the AAS format:

Armstrong et al. 2018, TGAC/miso-lims: v0.2.153, Zenodo, doi:10.5281/zenodo.1492883, as developed on GitHub
