### ISSUE TITLE
ERROR MISO MVC update v0.2.159 ->v0.2.161

### ISSUE THREAD

**Issue by bmatlas** [TGAC/miso-lims#1824]
Hi all,

while updating v0.2.159 to v0.2.161 MISO MVC failed. Can you help?

Thanks,
Tina

`[ERROR] Failed to execute goal on project miso-web: Could not resolve dependencies for project uk.ac.bbsrc.tgac.miso:miso-
web:war:0.2.161: Failed to collect dependencies for [org.kohsuke.metainf-services:metainf-services:jar:1.1 (compile?), aop
alliance:aopalliance:jar:1.0 (compile), com.sun.jersey:jersey-client:jar:1.19 (compile), com.sun.jersey.contribs:jersey-ap
ache-client:jar:1.19 (compile), com.sun.jersey.contribs.jersey-oauth:oauth-client:jar:1.19 (compile), com.sun.jersey.contr
ibs.jersey-oauth:oauth-signature:jar:1.19 (compile), commons-fileupload:commons-fileupload:jar:1.2.1 (compile), commons-ht
tpclient:commons-httpclient:jar:3.1 (compile), commons-logging:commons-logging:jar:1.1.1 (compile), io.prometheus:simplecl
ient:jar:0.0.21 (compile), io.prometheus:simpleclient_hotspot:jar:0.0.21 (compile), io.prometheus:simpleclient_servlet:jar
:0.0.21 (compile), io.prometheus:simpleclient_hibernate:jar:0.0.21 (compile), io.prometheus.jmx:collector:jar:0.9 (compile
), javax.servlet.jsp:javax.servlet.jsp-api:jar:2.3.1 (provided), javax.servlet:jstl:jar:1.2 (compile), javax.servlet:javax
.servlet-api:jar:3.1.0 (provided), javax.ws.rs:jsr311-api:jar:1.1.1 (compile), log4j:log4j:jar:1.2.16 (compile), net.sf.js
on-lib:json-lib:jar:jdk15:2.4 (compile), org.apache.poi:poi-ooxml:jar:3.6 (compile), org.aspectj:aspectjweaver:jar:1.6.12 
(compile), com.fasterxml.jackson.core:jackson-core:jar:2.8.6 (compile), com.fasterxml.jackson.core:jackson-databind:jar:2.
8.6 (compile), com.fasterxml.jackson.core:jackson-annotations:jar:2.8.6 (compile), com.google.guava:guava:jar:22.0 (compil
e), io.github.bonigarcia:webdrivermanager:jar:2.2.4 (test), org.hibernate:hibernate-core:jar:4.2.21.Final (compile), org.j
dom:jdom:jar:1.1 (compile), org.seleniumhq.selenium:selenium-java:jar:3.14.0 (test), org.slf4j:slf4j-api:jar:1.6.1 (compil
e), org.springframework:spring-beans:jar:4.3.18.RELEASE (compile), org.springframework:spring-context:jar:4.3.18.RELEASE (
compile), org.springframework:spring-core:jar:4.3.18.RELEASE (compile), org.springframework:spring-jdbc:jar:4.3.18.RELEASE
 (compile), org.springframework:spring-test:jar:4.3.18.RELEASE (test), org.springframework:spring-web:jar:4.3.18.RELEASE (
compile), org.springframework:spring-webmvc:jar:4.3.18.RELEASE (compile), org.springframework.integration:spring-integrati
on-core:jar:4.3.17.RELEASE (compile), org.springframework.security:spring-security-config:jar:4.2.7.RELEASE (compile), org
.springframework.security:spring-security-core:jar:4.2.7.RELEASE (compile), org.springframework.security:spring-security-l
dap:jar:4.2.7.RELEASE (compile), org.springframework.security:spring-security-taglibs:jar:4.2.7.RELEASE (compile), org.spr
ingframework.security:spring-security-web:jar:4.2.7.RELEASE (compile), uk.ac.bbsrc.tgac.miso:core:jar:0.2.161 (compile), u
k.ac.bbsrc.tgac.miso:integration-tools:jar:0.2.161 (compile), uk.ac.bbsrc.tgac.miso:miso-dto:jar:0.2.161 (compile), uk.ac.
bbsrc.tgac.miso:miso-service:jar:0.2.161 (compile), uk.ac.bbsrc.tgac.miso:sqlstore:jar:0.2.161 (compile), uk.ac.tgac.stats
db:statsdb-api:jar:1.1 (compile), xml-apis:xml-apis:jar:1.4.01 (compile), mysql:mysql-connector-java:jar:5.1.10 (test), or
g.mockito:mockito-core:jar:1.10.19 (test), junit:junit:jar:4.12 (test)]: Failed to read artifact descriptor for net.source
forge.fluxion:fluxion-spi:jar:1.0-alpha-3: Could not transfer artifact net.sourceforge.fluxion:fluxion-spi:pom:1.0-alpha-3
`

**Comment by djcooke** [comment]
Looks like this is because the hasbanana and TGAC repositories are down. Fortunately these repositories are no longer used in version v0.2.162. I've just now created a release for v0.2.162 and suggest upgrading to this version instead as it should build fine.

Closing the ticket for now. Please reopen if you have additional related problems.

**Comment by bmatlas** [comment]
Update 0.2.159 ->0.2.162 works. Thanks.
