### ISSUE TITLE
Q: What are the differences in Run Scanner from 1.1.0 to 1.3.0?

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1864]
I have not found any details on that. Thanks.

**Comment by apmasell** [comment]
Sorry. We're updating the change log retroactively:
https://github.com/oicr-gsi/runscanner/pull/41

**Comment by djcooke** [comment]
Thanks for pointing this out. The updated release notes are merged and this should be kept up-to-date for future releases: https://github.com/oicr-gsi/runscanner/blob/master/RELEASE_NOTES.md

Please file future Run Scanner issues in the [Run Scanner repository](https://github.com/oicr-gsi/runscanner)
