### ISSUE TITLE
Q: addSequencingParameters() for PacBio

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1871]
Can you give me an example on how you guys define "sequencing parameters" for `PacBio` runs?
All our runs are default, `Custom (see notes)`.

I was not able to (succesfully) apply `addSequencingParameters` for that purpose...

If `addSequencingParameters` is only working for `Illumina` runs, is there a safe way to add sequencing parameters for `PacBio` manually?

**Comment by djcooke** [comment]
Hello,

I am not experiencing any issues in testing the `addSequencingParameters` procedure. It should be ok for any platform/instrument. Are you still experiencing this issue? If so, which version of MISO is it on, and what is the full command you are trying to run?

**Comment by sklages** [comment]
As an example I have tried to add the following:
```
CALL addSequencingParameters('ISO-Seq','PacBio','Sequel',5000,0,'v2');
```
This results in an error in UI: `An unexpected error has occurred. If the problem persists, please report it to your MISO administrators` when clicking any PacBio run.

`miso_debug.log` states:
```
2019-04-08 16:50:54 ERROR: Returning error page for exception
org.springframework.dao.InvalidDataAccessApiUsageException: Unknown name value [v2] for enum class [uk.ac.bbsrc.tgac.miso.core.data.IlluminaChemistry]; nested exception is java.lang.IllegalArgumentException: Unknown name value [v2] for enum class [uk.ac.bbsrc.tgac.miso.core.data.IlluminaChemistry]
[...]
Caused by: java.lang.IllegalArgumentException: Unknown name value [v2] for enum class [uk.ac.bbsrc.tgac.miso.core.data.IlluminaChemistry]
[...]
```
So probably I used it wrong .. I did not use completely uppercase 'PACBIO' as stated in admin guide, but that seems not to be a problem, as I see it correctly in the database.

**Comment by sklages** [comment]
OK, I cannot oopen Illumina runs neither :-( 
Is there a way to safely modify or delete these parameters?

**Comment by djcooke** [comment]
Try using a capital V in 'V2', or change this to 'UNKNOWN' instead if that makes more sense. The chemistry values were intended for Illumina, so I'm guessing they don't make sense for PacBio.

**Comment by djcooke** [comment]
I am hoping to add UI to more safely add things like sequencing parameters in the future. We have a fairly large backlog of feature requests to prioritise however, so I'm not sure when this will happen.

**Comment by sklages** [comment]
Just deleted the entry in the database as there are no other entries created in addSequencingParameters()..

And yes, I changed it to uppercase `V2`  .. and it worked .. that was simple (though not very obvious).

thanks :+1:
