### ISSUE TITLE
if I want to run in Virtual Box, how can I open the browser?

### ISSUE THREAD

**Issue by DawnEve** [TGAC/miso-lims#320]
if I want to run in Virtual Box, how can I open the browser?
As the Ubuntu used in the image has no GUI now.

**Comment by DawnEve** [comment]
In fact, I already use the bridged mode, but the browser says "ERR_CONNECTION_REFUSED".

the screenshot is here:
http://agetouch.blog.163.com/blog/static/22853509020166266335723/

I think I know the reason: the port is 8080 not 8090.

**Comment by apmasell** [comment]
I will correct the instructions. Thanks.
