### ISSUE TITLE
Can't batch QCing sample or library

### ISSUE THREAD

**Issue by Hoxus** [TGAC/miso-lims#562]
Hi,

Sorry for my english, again.I already writed to you before (https://github.com/TGAC/miso-lims/issues/508), and I followed recomandation, so I can install.
MISO is my first choice, by far (I tested Gnomex, Bika, openlims, openBIS, etc.) and your recent improvements are really great. So I would like to use it, if I could.
I just received a new computer, and I would like to run MISO on a light linux virtualbox. Maybe it's an error to run it with virtual system, I don't know, but I think it will be easier to take snapshot, make backup, and clone before update. I already install it on Xubuntu, and it's work.

First, when I am on project page, with my sample, I see a list of option in the top right corner of sample list.

> Add Samples, Get Bulk Sample Input Form, Import Bulk Sample Input Form, Export Sample QC Sheet, Import Sample QC Sheet, Get Information Form, Import Information Form, Receive Samples, QC Samples, Add Libraries, Import Library Sheet, Print Barcodes

If I choose "QC samples", I see a table with a row by sample. But when I fill with some (false, it's a test) informations, I get an error, like that:

![2016-11-24 17-09-15 miso qc sample](https://cloud.githubusercontent.com/assets/10241614/20620987/c2d83fd8-b2fc-11e6-8184-f955f96c89b6.png)

Maybe I have make a mistake, but I try and retry, I can't validate this step with this form.

The "Export Sample QC Sheet" don't work, too: I can't see my sample. If I write something in filter, I can see samples, but can't add them.

I think it's trivial, because it's work when I click on each sample, and fill information one by one. But it's not handy.

Second, after QCing samples one by one, I get the same kind of error message when I QCing library:

![161125 miso qc library](https://cloud.githubusercontent.com/assets/10241614/20625655/fe3f3ce4-b314-11e6-912e-19d5fc041280.png)

Could you look at this problem, and say me if I made a mistake ?

Many thanks.

PS: I am familiar with web server, php and so on, but perhaps at only an intermediate level. So I'm pretty sure I can't efficiently help you.
All I can offer is to write a alternative installation guide for dummy. Let me know.

**Comment by frankie13** [comment]
Hey Hoxus - we have a release coming up really soon and are currently doing rounds of testing.
I will ask our lab to check these issues out and get back to you.

Thanks!

**Comment by frankie13** [comment]
OK!  I've done some investigation and the problem lies with the AllowAnythingNamingScheme specified in miso.properties.
It seems to be incompatible with QC Samples - for some reason.  I will investigate further...

**Comment by Hoxus** [comment]
Thanks you for your efforts.
So, if I understand, it's will work if I enable an other naming scheme ?
I have no access to my "work" computer, I will test as soon I could.

**Comment by frankie13** [comment]
Yes, I tested against our default build and (which uses DefaultEntityNamingScheme) and we don't seem to have any problems.  This would suggest the AllowAnythingNamingScheme causes problems further down the line.  There is some more information on naming schemes in the documentation: https://github.com/TGAC/miso-lims/blob/develop/docs/_posts/2016-01-11-admin-manual.md#naming-schemes

**Comment by Hoxus** [comment]
Hi,

Thank you very much for having a glance to this (maybe not) problem.
I come back to apologize for my silence.
I had some hard times in work and other (I'm a dad now), with huge amount of things to do. The LIMS is not a major priority in my team, I need to focus on other analyses, and I will re-test next week, or during christmas holidays.

Again, thanks !
