### ISSUE TITLE
Cannot change admin password or create user on local instance

### ISSUE THREAD

**Issue by diehlsa** [TGAC/miso-lims#631]
Hello,

the manager of our in-house sequencing facility wants to use MISO, so I have set up a local instance as described in docs/_posts/2016-01-11-admin-manual.md.

However, when I change the password of the default admin user, it has no effect. Changing the email address works. I also cannot create a new user, the error message I get is "Cannot create user - user isn't an admin.". Unfortunately the stack trace isn't helpful to me.

Thanks in advance for your help!

**Comment by djcooke** [comment]
Hello and thanks for reporting these bugs. We are currently working on a major update to some back-end code which will cover these issues.

**Comment by diehlsa** [comment]
Ok, thanks for the quick reply!

**Comment by apmasell** [comment]
We've corrected this bug. It will appear in the next release we put on Docker.
