### ISSUE TITLE
NPE when trying to list created Submissions

### ISSUE THREAD

**Issue by froggleston** [TGAC/miso-lims#848]
An NPE is thrown by the SQLTgacSubmissionDAO when trying to retrieve a previously created Submission object that contains a Pool for any platform that isn't Illumina, 454 or SOLiD. The NPE occurs at l 437:

`if (experiment.getPool().getId() == newPool.getId()) { ... }`

Caused by 

`public Pool getPoolByExperiment(Experiment e) { ... }`

in SQLPoolDAO.

**Comment by djcooke** [comment]
Hi Rob,

Which version of MISO is this on?

SQLTgacSubmissionDAO was replaced with HibernateSubmissionDao in v0.2.43. SQLPoolDAO has similarly been replaced by HibernatePoolDao

**Comment by froggleston** [comment]
Hey Dillan,

This is on our production build still running from master, as we need to yet migrate to develop.

Cheers,

Rob

**Comment by froggleston** [comment]
If I try it on our dev box (0.2.58-SNAPSHOT), I get the following error when trying to add a new Submission:

`No row with the given identifier exists: [uk.ac.bbsrc.tgac.miso.core.data.impl.UserImpl#116]; nested exception is org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [uk.ac.bbsrc.tgac.miso.core.data.impl.UserImpl#116]

    org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:196)
    org.springframework.orm.hibernate4.HibernateExceptionTranslator.convertHibernateAccessException(HibernateExceptionTranslator.java:57)
    org.springframework.orm.hibernate4.HibernateExceptionTranslator.translateExceptionIfPossible(HibernateExceptionTranslator.java:44)
    org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
    org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213)
    org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
    org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    uk.ac.bbsrc.tgac.miso.webapp.context.PrometheusInterceptor.invoke(PrometheusInterceptor.java:34)
    org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
    org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
    org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
    org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
    uk.ac.bbsrc.tgac.miso.persistence.impl.HibernateSampleDao$$EnhancerBySpringCGLIB$$fb47657f.listAll()
    uk.ac.bbsrc.tgac.miso.core.manager.MisoRequestManager.listAllSamples(MisoRequestManager.java:474)`

**Comment by djcooke** [comment]
Oh, good ol' `UserImpl#116`. @frankie13 had some similar issues related to this. I think it turned out to be caused by missing SampleChangeLogs

**Comment by froggleston** [comment]
Ah, glad it's a known issue at least. Any related tickets I can look at?

**Comment by morgantaschuk** [comment]
No tickets in our JIRA, but there's this exchange in Slack: https://miso-lims.slack.com/archives/C0LAPN9LY/p1488385447001081
