### ISSUE TITLE
handling high throughput screening dataset 

### ISSUE THREAD

**Issue by vipints** [TGAC/miso-lims#854]
Thanks for this nice work. Very easy to instantiate the demo instance. I am thinking about using miso-lims for managing the screening dataset from different types of well plates (96, and 384). Do you provide support for this. 
Thanks, Vipin

**Comment by morgantaschuk** [comment]
Hi @vipints,

At the moment, MISO's plate support is limited. However, you can configure 'Boxes' to have any size you want. Currently we have 8x8, 9x9, and 8x12. We haven't tested it with any size larger than that so far.

If you have any developers in-house, we welcome collaborators who would like to join us in developing new features. If not, you can reach out to myself and @froggleston to discuss how to support development for your particular needs.

Cheers,
Morgan

**Comment by vipints** [comment]
Thank you @morgantaschuk! 

Let me start playing with the boxes. At the moment, the facility is more interested in the sample tracking of the high content screening experiments. Let me test with an example dataset from my side on the miso instance and I will get back to you. 

As of now, we have limited people to work on this. I am available to understand the codebase join as a collaborator for the improvement of features to handle the high content screening dataset. I will check with you few needs I have in my mind in order to deploy the package. 

Thanks for your response! 
Vipin

**Comment by vipints** [comment]
Sorry I got delay in reply back to you - I have tried to access create box page on a demo instance of `miso` running on a docker environment. I am unable to create boxes with specified number of size. `box size` and `box use` fields are showing up a drop down menu list but this is empty and not accepting any value. Anything wrong here.

**Comment by callunity** [comment]
Hi @vipints sorry for the delayed reply! You will have to add box use and box size to the database using the following SQL:
```
INSERT INTO BoxUse (alias) VALUES ('Test');
INSERT INTO BoxSize (`rows`,`columns`,scannable) VALUES (8,12,1);
```

If you're doing this on the Docker demo, you will have to first conenct to the MySQL Docker container that is running the database. You may find [this helpful](https://littletechblogger.wordpress.com/2016/02/26/docker-how-to-connect-to-a-mysql-running-container-using-mysql-command-line-client/).

**Comment by morgantaschuk** [comment]
Closing this issue for now.
