### ISSUE TITLE
Support for downstream sample analysis tracking

### ISSUE THREAD

**Issue by stevekm** [TGAC/miso-lims#965]
I've been looking through the documentation on MISO trying to figure out if it meets our intended use case or not; we want to track samples across multiple sequencing platforms, and across multiple downstream analyses. From what I read, it looks like MISO only supports tracking of sequencing samples out-of-the-box; is that the case? Is it possible to add tracking of samples across downstream analyses? And can you get per-machine tracking metrics as well? 

Sorry I realize this question would have been more appropriate for Slack, but I was unable to access the channel posted in the Readme.

**Comment by apmasell** [comment]
I'm not sure what kind of downstream analyses you are referring to. At it's present design, MISO's responsibility is finished after samples land on a sequencer. There's a built-in component called Analysis Server that was designed by TGAC/EI to pass processing off to computational analysis. At OICR, @oicr-gsi uses Pinery to export the MISO data to the SeqWare where computational analysis is done, but none of this data is visible from MISO (and there are no plans to change that).

I'm not sure what kind of per-machine metrics you need. There are a few reports built into MISO, but most of them are not maintained. If you were interested in sequencing quality metrics, that does _not_ exist.
